### ISSUE TITLE
Rename SharedMemory* types to Shm*

### ISSUE THREAD

**Issue by yellowhatter** [eclipse-zenoh/zenoh#1014]
### Describe the release item

In order to shorten type names as we did with `ZSliceShm` -> `ZShm`, I propose to do `SharedMemory*` -> `Shm*` renaming.

**Comment by yellowhatter** [comment]
@Mallets what would you say?

**Comment by Mallets** [comment]
I think it's ok to rename it to a shorter name. `shm` is already an established short version of `shared memory`.

**Comment by Mallets** [comment]
Closed by #1095
