### ISSUE TITLE
Zenoh fails to reconnect when running with `lowlatency` and without scouting/gossip

### ISSUE THREAD

**Issue by esemeniuc** [eclipse-zenoh/zenoh#1024]
### Describe the bug

I'm running pub/sub example, meant for servers running in production. Multicast and gossip expose more risk, so they are disabled. I'm have trouble reconnecting after the publisher restarts when in `low_latency` mode. 

### To reproduce

Please see this diff: https://github.com/eclipse-zenoh/zenoh/compare/0.11.0-rc.2...jito-labs:zenoh:eric/bug-repro?expand=1

1. Start Publisher on machine 1
2. Start Subscriber on machine 2, let it receive messages
3. Restart Publisher on machine 1
4. Subscriber never reconnects

### System info

Arch, linux 6.6.28-1-lts
Rust version: using default in toolchain file

**Comment by YuanYuYuan** [comment]
The issue doesn't occur with the default universal transport. I'll investigate the reason.

**Comment by esemeniuc** [comment]
I noticed that the publisher can use low latency mode without issues. The subscriber is the one bugging out.

**Comment by YuanYuYuan** [comment]
> I noticed that the publisher can use low latency mode without issues. The subscriber is the one bugging out.

Yes, it is. We didn't handle the link closing properly. #1030 should fix this issue.
