### ISSUE TITLE
Publication cache

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh#103]
To support the QueryingSubscriber use cases described in #102, we require the possibility to declare a Publisher that will also  maintain a local cache of its publications (at least 1 sample per path) and declare a queryable to return the content of this cache on queries.

**Comment by kydos** [comment]
@JEnoch , I was thinking a bit more about this and there are a few use cases for which it would make sense to have a "_storage_" that behaves as a cache. We need to workout the details as there are some non-trivial points to be addressed when queurying a set of resources...
