### ISSUE TITLE
make multicast scouting ttl configurable

### ISSUE THREAD

**Issue by jeremiah-wooten** [eclipse-zenoh/zenoh#1040]
### Describe the feature

I have a use case for zenoh where I need the multicast scouting to traverse a router, but the time-to-live on the multicast packets is left as the default, which is only 1. I would like if this value was configurable in the zenoh config. Without this, I would have to add some kind of special multicast routing protocol, which I would like to avoid if possible.

**Comment by gui81** [comment]
Same here.  If the multicast IP and port are configurable, allowing someone to move out of the link-local multicast range (224.0.0.0/24), then TTL can be important if there is more than one hop.

It looks like there is a pull request here: https://github.com/eclipse-zenoh/zenoh/pull/1032
