### ISSUE TITLE
Allow for setting Congestion Control on `Publisher::put` builders (`Publication`s)

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh#1041]
### Describe the feature

Today the API allows for calling `.congestion_control(..)` on the result of a `Session::put` but not a `Publisher::put`.

**Comment by Mallets** [comment]
Closing this issue for the time being, see https://github.com/eclipse-zenoh/zenoh/pull/1124. It may be rediscussed in the future.
