### ISSUE TITLE
Timeout for queries

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh#106]
Queries should have a timeout. A default one or a user-specified one.
If a query doesn't complete before the timeout, he should be notified and the query should be canceled.

Similarly, the QueryingSubsriber should be configurable with a timeout for its queries (or the default timeout should apply).

**Comment by adlinknorm** [comment]
Hi @Mallets, do we have any schedule for this function? This is important for our project. Thanks!  :)

**Comment by JEnoch** [comment]
Implemented by #347 and therefore available since `0.6.0-beta.1`
