### ISSUE TITLE
consider completely removing `Value` type, use `QueryError` instead

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1064]
### Describe the release item

https://github.com/wyfo wrote:

Joseph — Yesterday at 3:43 PM
modules enccoding and value only contains one type. I don't know if it's good, but I don't know where to put them instead.
Actually, Value type should disappear of the public interface, because we removed it everywhere to replace it by ZBytes + Encoding.
The only place where Value remain a thing is in Reply::result.
Denis Biryukov — Yesterday at 3:48 PM
maybe  we should rename it into something like ReplyError ? or QueryError ? 
Joseph — Yesterday at 3:49 PM
Yes, that's what I was writing.
I prefer QueryError to ReplyError though
Joseph — Yesterday at 4:08 PM
Also, ValueBuilder should be reworked

**Comment by Mallets** [comment]
Closed by #1119
