### ISSUE TITLE
config reexports zenoh_config::* , which leaks many types. To be verified and eventually reworked.

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1069]
### Describe the release item

Types in `mod config` should be reexported explicitly

**Comment by milyin** [comment]
work started in PR https://github.com/eclipse-zenoh/zenoh/pull/1402

**Comment by fuzzypixelz** [comment]
Resolved in https://github.com/eclipse-zenoh/zenoh/pull/1419.
