### ISSUE TITLE
Not clear the difference between `selector::Properties` and `selector::Parameters`

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1070]
### Describe the release item

mod selector exports `Properties` and `Parameters`which is wrapper for properties. This is hard to understand, why

**Comment by Mallets** [comment]
`Properties` should not be exposed and kept internal. Only `Parameters` should be exposed.

**Comment by wyfo** [comment]
@Mallets I think the issue is that `Properties` is currently exposed as the `Deref` target of `Parameters`, and as the only way to construct a `Parameters` instance via the `From<impl Into<Properties>>` implementation.

**Comment by Mallets** [comment]
It is being reworked in #1100
