### ISSUE TITLE
possible misuse of `#[zenoh_macros::unstable]` and `#[zenoh_macros::unstable_doc]`

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1074]
### Describe the release item

The `#[zenoh_macros::unstable]` is fully equal to `#[cfg(attribute="unstable")]`
The `#[zenoh_macros::unstable_doc]` gives additional functionality: it adds information to documnatation that this is unstable feature.
Also just `#[cfg(attribute="unstable")]` is actively used

The proposal is:
- remove `#[zenoh_macros::unstable]`: replace it to  `#[cfg(attribute="unstable")]` for pieces of code and to `#[zenoh_macros::unstable_doc]` where the documentation should be corrected.
- add check to `#[zenoh_macros::unstable_doc]` forbidding it's usage if no documentation for item exists

**Comment by wyfo** [comment]
> The `#[zenoh_macros::unstable]` is fully equal to `#[cfg(attribute="unstable")]`

I'm not sure to following you. `#[zenoh_macros::unstable]` is equivalent to `#[cfg(attribute="unstable")]#[zenoh_macros::unstable_doc]`, not just `#[cfg(attribute="unstable")]`.

If I've understood correctly, `zenoh_macros::unstable_doc` is for items of "unstable" crates, like `zenoh-shm`, which are reexported in `zenoh`. These crate don't have a `unstable` feature, so `zenoh_macros::unstable` would not have sense.
So both are needed.

> add check to `#[zenoh_macros::unstable_doc]` forbidding it's usage if no documentation for item exists

I'm +1 on that.

**Comment by milyin** [comment]
About equivalence - it was my mistake, zenoh_macros::unstable also updates documentation.
Yes, I found that we can't remove `unstable_doc` - it seems if was specially created for adding "unstable" documentation comment to crate without scattering unstable feature everywhere.
About forbidding usage of macro when no documentation - seems like it adds more problems than solves. It becomes easy to add documentation and forget to add `zenoh_macros::unstable`.
So closing it as not a bug.
