### ISSUE TITLE
[dev/1.0.0]`Encoding::from(&str)` skip unsupported encoding

### ISSUE THREAD

**Issue by wyfo** [eclipse-zenoh/zenoh#1078]
### Describe the release item

https://github.com/eclipse-zenoh/zenoh/blob/9bcfdc78ba73957cb49fa475e9192221c75baa58/zenoh/src/api/encoding.rs#L642-L644

This behavior is quite unintuitive. I think we should remove this `From<&str>` implementation and replace it with a `FromStr`.

@Mallets @milyin 

EDIT: we should remove this `From<&str>` implementation and raise an error in `FromStr` if the encoding is not supported.

**Comment by wyfo** [comment]
> FromStr is already implemented. 

I know, my point is that we should not skip unsupported encoding silently, we should raise and error instead, so only use a "raising" `FromStr` implementation.

**Comment by wyfo** [comment]
If I read the code correctly, `Encoding::from("my_encoding")` will return `Encoding::ZENOH_BYTES`. Is that really what we want?

**Comment by wyfo** [comment]
@milyin think we maybe should then put the unrecognized string in schema instead of discarding it. I also think that's a better solution than what we have now.

**Comment by Mallets** [comment]
Closed by #1102
