### ISSUE TITLE
ZSlice and ZBytes are internal now. Can we avoid their usage in shm examples

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1081]
### Describe the release item

It was decided to move `ZSlice` and `ZBuf` into `internal` mod. But these structs are used in shm examples.
Should we fix examples or the decision to make these things internal doesn't work for shm?
@yellowhatter can you check?

**Comment by wyfo** [comment]
I think you wrote `ZBbytes` instead `ZBuf`.  `ZBytes` is meant to be public, it appears everywhere in the API. `ZBuf` is the internal implementation of `ZBytes`.

**Comment by yellowhatter** [comment]
@milyin examples fixed: #1129
