### ISSUE TITLE
Unable to run ping/pong with size 65536 if enabling lowlatency

### ISSUE THREAD

**Issue by evshary** [eclipse-zenoh/zenoh#1087]
### Describe the bug

If we enable the lowlatency mode in the config, the ping/pong test will fail when the size is 65536.

### To reproduce

1. Create a config with

```
lowlatency: true,
qos: {
    enabled: false,
}
```

2. Run pong

```sh
./target/release/examples/z_pong -c config.json5
```

3. Run ping

```sh
./target/release/examples/z_ping 65536 -c config.json5
```

The ping/pong test doesn't work.

### System info

* Ubuntu 22.04
* Zenoh: main branch

**Comment by evshary** [comment]
@Mallets  @yellowhatter  Do you remember the fragmentation is supported in lowlatency mode?

**Comment by yellowhatter** [comment]
> @Mallets @yellowhatter Do you remember the fragmentation is supported in lowlatency mode?

Currently there is no fragmentation for lowlatency transport

**Comment by evshary** [comment]
> Currently there is no fragmentation for lowlatency transport

@yellowhatter  Thank you for the explanation. Then I think this should be the limitation currently. I'll add some notes in the configuration file.
