### ISSUE TITLE
CI fail after adding `internal` feature

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1103]
### Describe the bug

https://github.com/eclipse-zenoh/zenoh/actions/runs/9438775135/job/25996118849?pr=1099
This could also be related to https://github.com/eclipse-zenoh/zenoh/issues/940

### To reproduce

-

### System info

-

**Comment by fuzzypixelz** [comment]
Fixed in https://github.com/eclipse-zenoh/zenoh/pull/1105.
