### ISSUE TITLE
Suggestion: `internal::Value` destructor into components. 

### ISSUE THREAD

**Issue by Charles-Schleich** [eclipse-zenoh/zenoh#1125]
### Describe the feature

Once https://github.com/eclipse-zenoh/zenoh/pull/1119 lands, It May be useful to be able to destruct a `Value` into its `payload` and `encoding`, taking ownership of both upon destruction.
Currently the only option is to take a reference to the `payload` and `encoding`, forcing a `.clone()` in circumstances where destructing would be preferred.

**Comment by wyfo** [comment]
Because `Value` becomes *internal*, it could also make sense to make its fields public.

**Comment by Mallets** [comment]
@Charles-Schleich can you submit a PR?

**Comment by Charles-Schleich** [comment]
Resolved by [1178](https://github.com/eclipse-zenoh/zenoh/pull/1178)
