### ISSUE TITLE
Bump plugins to Zenoh 1.0

### ISSUE THREAD

**Issue by evshary** [eclipse-zenoh/zenoh#1141]
### Describe the release item

The issue tracks the progress of bumping the Zenoh plugins:

- [x] mqtt https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/128 , https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/131
- [x] webserver https://github.com/eclipse-zenoh/zenoh-plugin-webserver/pull/94
- [x] ros1 - https://github.com/eclipse-zenoh/zenoh-plugin-ros1/pull/87
- [x] dds https://github.com/eclipse-zenoh/zenoh-plugin-dds/pull/256
- [x] ros2dds https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/167
- [x] influx-db https://github.com/eclipse-zenoh/zenoh-backend-influxdb/pull/130 - CI error
- [x] rocks-db https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/pull/106 - fix requests
- [x] filesystem - https://github.com/eclipse-zenoh/zenoh-backend-filesystem/pull/121 - fix request
- [x] s3 https://github.com/eclipse-zenoh/zenoh-backend-s3/pull/96

**Comment by gabrik** [comment]
- [ ] https://github.com/eclipse-zenoh/zenoh-backend-filesystem/pull/130 

I think this should be in the list.
