### ISSUE TITLE
Add zenoh related debs for aarch64.

### ISSUE THREAD

**Issue by ZhenshengLee** [eclipse-zenoh/zenoh#117]
Since there are zenoh index file for `amd64` and `armhf` in the eclipse mirror, which I visited through `https://mirrors.tuna.tsinghua.edu.cn/eclipse/zenoh/zenoh/latest/`.

I suggest to add aarch64 debs for nvidia jetson devices, as time comsuming of compiling is too long.

Thanks.

> 82 Mins on an NVIDIA Xavier

_Originally posted by @vinnnyr in https://github.com/eclipse-zenoh/zenoh/issues/76#issuecomment-812930855_

**Comment by JEnoch** [comment]
Debian files for `arm64`, `armhf` and `armel` are now available for the latest [0.5.0-beta.9 release](https://github.com/eclipse-zenoh/zenoh/releases/tag/0.5.0-beta.9).
A new debian repo has been set-up on https://download.eclipse.org/zenoh/debian-repo containing all the .deb for all zenoh repos.
Instructions to use it have been updated on https://zenoh.io/docs/getting-started/installation/#ubuntu-or-any-debian
