### ISSUE TITLE
Admin space keys remapping

### ISSUE THREAD

**Issue by OlivierHecart** [eclipse-zenoh/zenoh#1190]
### Describe the release item

Change all the admin and plugin key expressions to be in the following spaces:
`@/<zenohid>/router/**` 
`@/<zenohid>/peer/**` 
`@/<zenohid>/client/**` 
`@/<zenohid>/dds/**` 
`@/<zenohid>/ros1/**` 
`@/<zenohid>/ros2/**` 
`@/<zenohid>/@ros2_pub_cache/**` 
`@/<zenohid>/@ros2_lv/**` 
`@/<zenohid>/mqtt/**` 
`@/<zenohid>/@storage/digest/**` 
`@/<zenohid>/@storage/align/**`

The reasons behind those changes are:
- Gather all internal management keys under a common prefix.
- Allow to access all infos about a Zenoh node in one `get`.
- Allow to apply a ZenohID based routing to the `@` namespace in the future without needing to change keys.

**Comment by Mallets** [comment]
Closed by #1209
