### ISSUE TITLE
zenoh-codec-1.0.0-alpha.2: unsafe function not covered

### ISSUE THREAD

**Issue by roby2014** [eclipse-zenoh/zenoh#1234]
### Describe the bug

```
   Compiling zenoh-codec v1.0.0-alpha.2
   Compiling zenoh-config v1.0.0-alpha.2
error[E0133]: call to unsafe function `with_slot` is unsafe and requires unsafe function or block
   --> /home/roby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zenoh-codec-1.0.0-alpha.2/src/core/zint.rs:115:9
    |
115 | /         writer.with_slot(VLE_LEN_MAX, move |buffer| {
116 | |             let mut len = 0;
117 | |             while (x & !0x7f_u64) != 0 {
118 | |                 // SAFETY: buffer is guaranteed to be VLE_LEN long where VLE_LEN is
...   |
141 | |             len
142 | |         })?;
    | |__________^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior

For more information about this error, try `rustc --explain E0133`.
error: could not compile `zenoh-codec` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### To reproduce

Use the crate and try to build.

### System info

- `zenoh-codec v1.0.0-alpha.2`
- `Linux roby-thonkcentre 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by roby2014** [comment]
I think this error ocurred after I also upgraded my `zenoh-plugin-rest` to `1.0.0-alpha.2` (?)

**Comment by diogomatsubara** [comment]
@roby2014 The `1.0.0-alpha.2` crate is busted. It was released by mistake and will be yanked from crates.io. This week we will release a new alpha properly. Apologies for the inconvenience

**Comment by diogomatsubara** [comment]
`1.0.0-alpha.4` has been released correctly so you shouldn't see any errors. Let me know if it works for you @roby2014. Please re-open if you continue to see issues
