### ISSUE TITLE
Failure to undeclare Liveliness Subscribers

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh#1282]
### Describe the bug

https://github.com/eclipse-zenoh/zenoh/blob/502d3be20b78f2873ec069cbcd5fefd308ecf5c7/zenoh/src/api/session.rs#L1239-L1243

Only non-Liveliness Subscribers are checked.

### To reproduce

1. Declare a Liveliness Subscriber
2. Undeclare it.

### System info

- ref: 502d3be20b78f2873ec069cbcd5fefd308ecf5c7

**Comment by YuanYuYuan** [comment]
Relevant issue https://github.com/ZettaScaleLabs/rmw_zenoh/issues/2
