### ISSUE TITLE
Documentation of protocol itself?

### ISSUE THREAD

**Issue by martinjaeger** [eclipse-zenoh/zenoh#130]
Hi Zenoh team. Just discovered Zenoh because of a Zephyr-related tweet and I find it very exciting!

I'm most interested to understand in detail how the protocol (especially the lower layer zenoh.net) works, but I didn't find any details regarding packet routing, frame formats, headers etc. on [zenoh.io](https://zenoh.io). Is there some other place where this is documented? Is there something like an RFC for the protocol?

BTW: We are also working on a low-overhead protocol called [ThingSet](https://thingset.io) to seamlessly interact with resource-constrained devices over different lower layers including CAN, serial, LoRaWAN etc.. I'd be very interested to see how both approaches could work together.

**Comment by kydos** [comment]
Hello @martinjaeger,

    We used to have a protocol specification for zenoh, but as the protocol has evolved quite rapidly, we retired the spec from our website as it had become obsolete. That said, we plan to update it,  since as you may imagine we get often this request -- thus stay tuned!

Concerning your initiative on ThingSet, I'll take a look as I'd like to learn more about it and will get back to you.

Take Care!

**Comment by Mallets** [comment]
Closing this issue since the ongoing work on new protocol refactoring is tracked by #157.
Please refer to that issue for further information.
