### ISSUE TITLE
`zenoh::pubsub::Reliability` option is decided to be unstable

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1307]
correct in all bindings
- [x] zenoh
- [x] zenoh-c
- [x] zenoh-cpp

check
- [x] zenoh-pico

**Comment by wyfo** [comment]
Why?

**Comment by milyin** [comment]
> Why?

Better to ask @Mallets and@OlivierHecart for detais. I think it's related to this draft PR which is going to change this functionality somehow https://github.com/eclipse-zenoh/zenoh/pull/1305

**Comment by Mallets** [comment]
Reliability is still not finalized and it may change in the future. So better marking the API as unstable for the time being.
