### ISSUE TITLE
zn_ping/zn_pong should use the sync API

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh#132]
We should update zn_ping/zn_pong to leverage the synch API. This allow to have a better estimation of the Round-trip time as we limit the interferences from the async-std scheduler.

**Comment by Mallets** [comment]
Fixed in [3af808b8fa8e4e9d0225d90226cbe1313bb10807](https://github.com/eclipse-zenoh/zenoh/commit/3af808b8fa8e4e9d0225d90226cbe1313bb10807).
