### ISSUE TITLE
Feature: Default systemd service for zenoh router

### ISSUE THREAD

**Issue by Aposhian** [eclipse-zenoh/zenoh#142]
When running `zenohd` routers in a persistent network topology, it is desirable to configure `zenohd` as a service. It seems like it would be ergonomic to provide a default systemd service with the package install.

For the short term, it could simply use `Type=Simple`, but it would be great if it could use `Type=notify`, so it could notify the system when zenoh is ready.

**Comment by gabrik** [comment]
Hi @Aposhian, indeed having a service file for `zenohd` will simplify a lot of use-cases like yours.
We have created a PR (see #143) that implements a service file with `Type=Simple`, for `Type=Notify` we need more internal discussion as it requires to implement some logic in `zenohd`. 

Please feel free to check the code from the PR and let us know if it solves (or partially) your issue.
