### ISSUE TITLE
replication: perform initial alignment only on Replicated Storage

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh/zenoh#1463]
### Describe the feature

As discussed [here](https://github.com/eclipse-zenoh/zenoh/pull/1458#discussion_r1768290320), when a Storage is configured to be replicated, the first action it performs is to query any Storage (configured to be replicated or not) for data.

Maybe we should change this behavior, and add a dedicated queryable or variant to the `AlignmentQuery` specifically for this scenario. This would limit the reach of this initial alignment to Storage that are actually being replicated.

**Comment by Charles-Schleich** [comment]
Closed by https://github.com/eclipse-zenoh/zenoh/pull/1468
