### ISSUE TITLE
Unable to get attachment with iterator

### ISSUE THREAD

**Issue by evshary** [eclipse-zenoh/zenoh#1552]
### Describe the bug

In the test code, we can get the ZBytes with iterator.
https://github.com/eclipse-zenoh/zenoh/blob/1877831a3d723a0a90ced0a6a8cf04dd11852433/zenoh/src/api/bytes.rs#L206

However, we can't do the same thing while sending as an attachment.

### To reproduce

1. Modify `z_put.rs`
```rust
    println!("Putting Data ('{key_expr}': '{payload}')...");

    use zenoh::bytes::ZBytes;
    let buf1: Vec<u8> = vec![1, 2, 3];
    let buf2: Vec<u8> = vec![4, 5, 6, 7, 8];
    let mut writer = ZBytes::writer();
    writer.append(ZBytes::from(buf1));
    writer.append(ZBytes::from(buf2));
    let zbytes = writer.finish();

    // Refer to z_bytes.rs to see how to serialize different types of message
    session
        .put(&key_expr, payload)
        .attachment(zbytes)
        .await
        .unwrap();
```
2. Modify `z_sub.rs`
```rust
        if let Some(att) = sample.attachment() {
            let mut iter = att.slices();
            println!("");
            println!("first: {:?}", iter.next().unwrap());
            println!("second: {:?}", iter.next().unwrap());
            //let att = att.try_to_string().unwrap_or_else(|e| e.to_string().into());
            //print!(" ({})", att);
        }
        println!();
```
3. Run `z_sub.rs` and `z_put.rs`, `z_sub.rs` will panic since it can't get the second ZBytes. The first one and the second one are combined together.
```
Opening session...
Declaring Subscriber on 'demo/example/**'...
Press CTRL-C to quit...
>> [Subscriber] Received PUT ('demo/example/zenoh-rs-put': 'Put from Rust!')
first: [1, 2, 3, 4, 5, 6, 7, 8]
thread 'main' panicked at examples/examples/z_sub.rs:49:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### System info

Ubuntu 24.04

**Comment by DenisBiryukov91** [comment]
Zbytes::slices provides a slice iterator where each slice corresponds to a separate fragment. Zenoh does not provide any guarantee regarding fragment size since this is network-dependent. So the behavior is correct.
If you want to transmit structured data please consider using zenoh_ext::ze_serialize or  zenoh_ext::Serializer (which will likely provide the functionality you need).

**Comment by evshary** [comment]
Hi @DenisBiryukov91, I'm not sure whether this is expected. In the previous version, we can use iterator to do the same thing. I'm fine if we decide not to support this after transmitting via the network, but in this case, I'm wondering whether there is any meaning to support the iterator for ZBytes.

Anyway, I'll check why the behavior is changed after updating the version. Please let me know if you have any other idea.

**Comment by DenisBiryukov91** [comment]
@evshary ZBytes::slices() was different from ZBytes::iter(), and always worked this way (i.e. returned fragment of message - without any guarantees regarding their number or sizes - this is exactly what is written in the docs), it is provided to allow access to underlying data without any extra copy. 
After serialization refactoring we removed ZBytes::from_iter()/ ZBytes::iter() and replaced their functionality with zenoh_ext::ZSerializer/ZDeserializer.

**Comment by evshary** [comment]
@DenisBiryukov91 My bad. You shed some light on my blind spot of ZBytes!
I used to transform `Vec<T>` into `ZBytes` and send as attachment, and I thought we can only use `ZBytes::writer()` to do the similar thing.
However, `ZBytes::writer()` is not what I expected. It will have several ZSlice locally, but might be contiguous after some operations.
What I want is to have Vec<Vec<u8>>, which should use ZSerializer and ZDerializer as you said.

```rust
# Sender side
 let buf1: Vec<u8> = vec![1, 2, 3];
 let buf2: Vec<u8> = vec![4, 5, 6, 7, 8];
 let bufs = vec![buf1, buf2];
 let zbytes = z_serialize(&bufs);
# Receiver side
for v in z_deserialize::<Vec<Vec<u8>>>(att).unwrap().iter() {
    println!("{v:?}");
}
```

Thanks for your answer, and I think this should not be an issue.
