### ISSUE TITLE
the access to `Config` elements is internal now, add this to migration guide

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#1565]
### Describe the release item

From @kydos 

the following code does not compile:
```rust
fn main() {
    let mut c = zenoh::Config::default();
    c.set_mode(zenoh::config::WhatAmI::Client);
}
```
Found the issue, in 1.0.0 these APIs are internal and need to be activated via:
zenoh = { version = "1.0.0", features = ["internal", "internal_config"] }
We should have this on the Migration Guide.

**Comment by Mallets** [comment]
The API is marked as internal, so I'm not sure it should be covered in the migration guide.
IMHO it would be better to use `insert_json5` API also in our examples and eventually adding a dedicated examples showing how to programmatically configuring zenoh.

**Comment by samcarey** [comment]
> it would be better to use insert_json5

Why is `insert_json5` being promoted for manipulating a Rust struct?
Why not use setter methods for the individual fields, so the inserted fields and values are type-checked at compile time instead of being parsed from strings at runtime?
