### ISSUE TITLE
Feedback on concurrency-friendly design of v0.6.0

### ISSUE THREAD

**Issue by jerry73204** [eclipse-zenoh/zenoh#162]
Congratulations that v0.6.0 is released and I cannot wait to try it out on my projects. It see the new API gains more simplicity compared to v0.5.0. After testing it around, I'd like to share my feedback on haves and have-nots on current design.

## Shared `Session`

Let `Session` to be cloneable and be internally reference counted. It makes things easier when concurrent workers share a session.

```rust
let session = zenoh::open(config::default()).await?;

let workers = (0..n_workers).map(|_| {
    // In previous API, we have to
    // let session = Arc::new(session) then session.clone(),
    let session = session.clone();

    async move {
        session.put(key, data).await?;
        // omit
    }
});

futures::try_join_all(workers).await?;

```

The implementation could be done by using wrapped-`Arc` trick.

```rust

// `Session` is public to users. It holds the reference counted state and per-worker specific contexts.
#[derive(Clone)]
pub struct Session {
    pub(crate) inner: Arc<SessionState>
    // omit ..
}

// `SessionState` is a shared private struct that is reference counted.
struct SessionState {
    // omit ..
}

// Define operations and internal methods on state.
impl SessionState {
    async fn put(self: Arc<Self>, key_expr: K) { /* omit */ }
}

// `Session` exposes public methods and it delegate to private methods.
impl Session {
    pub async fn put(&self, key_expr: K) {
        self.state.put(key_expr).wait;
    }
}
```

If you cannot agree with this design, this is an alternative to let ref-counting to be explicit.

```rust
impl Session {
    pub fn make_ref_builder<'a>(&'a self) -> Builder<'a> {
        Builder { session: self }
    }

    pub fn make_owner_builder(self: Arc<Self>) -> OwnedBuilder {
        OwnedBuilder { session: self.clone() }
    }
}
```

## Initialization

The v0.6.0 currently adopts the builder pattern to construct construct subscribers. I would introduce [init struct pattern](https://xaeroxe.github.io/init-struct-pattern/) as an alternative. It separates mandatory and optional options in explicit syntax, and provides default values without boilerplate code. 

```rust
use serde::{Serialize, Deserialize};

// The config type defines "optional" attributes for a subscriber.
// The fields are not `Option<_>`. They are filled by default values in the beginning.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
struct SubscriberConfig {
    pub reliability: Reliability,
    pub sub_mode: SubMode,
}

// The default() generates default options for the config.
impl Default for SubscriberConfig {
    fn default() -> Self { /* omit */ }
}

// Using default options should be straightforward.
let subscriber: Subscriber = session.subscriber(key, Default::default()).await?;

// Partially fill values to customize. 
let config = SubscriberConfig {
    reliability: BestEffort,
    ..Default::default()
};
let subscriber: Subscriber = session.subscriber(key, config).await?;

imp Session {
    async fn subscriber(
        &self,
        key: IntoKeyExpr<'_>,       // mandatory option(s)
        config: SubscriberConfig    // optional options
        ) -> Result<Subscriber>
        {
        // Now it reads options directly without boilerplate unwrapping `Option<_>`s.
        let SubscriberConfig { reliability, sub_mode } = config;
    }
}
```

The init pattern can still be used to provide the builder API.

```rust
imp Session {
    async fn subscriber_builder<'a>(&'a self) -> SubscriberBuilder<'a> { /* omit */ }
}

struct SubscriberBuilder<'a> {
    session: &'a Session,
    config: SubscriberConfig,
}

impl SubscriberBuilder<'a> {
    pub reliability(self, reliability: Reliability) -> Self {
        Self {
            session: self.session,
            config: SubscriberConfig { reliability, ..self.config }
        }
    }
}
```

## Seamless `futures`-API

To write an concurrent producer-consumer example with v0.6.0 API, the code will look like this. 

```rust

let session = Arc::new(zenoh::open(config));
let key = "my_key";

let producer = {
    let session = session.clone();
    let key = key.clone();  // workaround ownership

    async move {
        data_source_stream
            .then(|data| async move { transform(data) })
            .try_scan(session |session, data| {
                let key = key.clone();

                // Actually it does not compile because session is `&mut Session`.
                // It is flawed design of futures API. We omit this issue for simplicity.
                async move {
                    session.put(key, data).await?;
                    Ok((session, ()))
                }
            })
            .try_for_each(|()| async move { Ok(()) })
            .await?;
    }
};

let consumer = {
    let session = session.clone();
    let key = key.clone();  // workaround ownership

    async move {
        session.subscribe(key)
        .await?
        .receiver()
        .try_for_each(|sample| async move { /* handle message */ })
        .await?;
    }
};

futures::try_join!(producer, consumer);
```

The code could be further simplified if we can take advantage of futures crate's Stream-to-Sink pattern.

```rust
let session = Arc::new(zenoh::open(config));
let key = "my_key";

let producer = {
    let publisher = session
        .publisher(&key, config)
        .await?;

    // The publisher provides a `send()` method.
    // Here we use sink API instead.
    data_source_stream
        .then(|data|  async move { transform(data) })
        .forward(publisher.into_sink())
};

let consumer = {
    let receiver = session.subscriber(&key, config).await?;

    // The receiver has a `recv()` method. User can choose to `recv()` or turn it to a stream.
    receiver.into_stream().try_for_each(|sample| async move { /* handle message */ })
};

futures::try_join!(producer, consumer);
```

`session.publisher(&key, config)` returns an actual publisher instead of a builder. It keeps an internal `Arc`-reference to session. In this way, the user does not need to work on lifetime issues on `key` and `session`.

It can integrate with init/builder pattern to enable one-liners.

```rust
// changing a few of options
session.publisher_builder(&key)
    .reliability(reliability)
    .build()
    .await?; 

// changing a lot of options
let config = SubscriberConfig {
    reliability,
    mode,
    local,
    ..Default::default()
};
session.publisher(&key, config);
```

With futures sink API, it makes directly forwarding to be straightforward.

```rust
let pub = session.publisher(pub_key, default()).await?;
let sub = session.subscriber(sub_key, default()).await?;
pub.into_stream().forward(sub.into_sink()).await?;
```

**Comment by OlivierHecart** [comment]
Thanks for your feedbacks @jerry73204 !

## Shared `Session`
In our very first versions of zenoh-rust, the session was cloneable and we had some debates if it should be the case or not. We finally decided that it should not be cloneable for the following reasons : 
1. If the session is cloneable and one of the clones is closed, then we need to handle errors if operations are called on the other clones afterward.
2. A non cloneable session allows us to restrict sub-entities (subscribers, ...) lifetimes to their parent session lifetime and so let rust compiler check for us that those sub-entities do not outlive their session. Otherwise we'd also have to handle errors if operations are called on sub-entities which parent session is closed.
3. We think it's better if the user explicitly puts it's zenoh session in an Arc to share it around. It seems it is the common practice in the rust community.

## Initialization
This is an interesting pattern. But we are not fully convinced. It fits quite well with initialization of entities like subscribers but fit less with other operations that also use the builder pattern like put() and get(). Another concern is that it would make the rust API even more different from other bindings.

## Seamless `futures`-API
On subscription side the SampleReceiver is already a stream and so we should be almost there to do what you propose. Or is there something missing ? 
On sending side, allowing to create a Sender that can be turned into a sink is indeed something useful that we could provide. We just don't think we should do this through the publisher (b.t.w note that we don't have a publisher anymore) but through another session operation. I'll try to provide something and see if I can come to something as elegant as your last piece of code.

Let us know what you think or if we missed the point of some of your feedbacks.

**Comment by jerry73204** [comment]
In terms of subscriber stream, there is an indirection of calling `subscriber.receiver()` to obtain the stream.

```rust
let mut subscriber = session.subscribe("/key/expression").await?;
subscriber.receiver().for_each(|_| async move { /* snip */ });
```

I would prefer that it's done in one call. Let the subscriber to be `Stream` (and `Iterator`), and also provides `close()`.

```rust
let subscriber = session.subscribe("/key/expression").await?;
subscriber.for_each(|_| async move { /* snip */ });
```

> A non cloneable session allows us to restrict sub-entities (subscribers, ...) lifetimes to their parent session lifetime and so let rust compiler check for us that those sub-entities do not outlive their session. Otherwise we'd also have to handle errors if operations are called on sub-entities which parent session is closed.

This is reasonable design to me. There is a catch that it disallows passing a subscriber to a spawned task. The borrow checker complains that the lifetime is not enough.

```rust
let session: Arc<Session> = /* snip */;
let mut subscriber = session.subscribe("/key/expression").await?;

task::spawn(async move {
    subscriber.receiver().for_each(|_| async move { /* snip */ });  // task::spawn() requires it to be 'static, but it does not
});
```

To remedy this, pass `Arc<Session>` to the spawned task instead and creates a subscriber within it. It adds an extra burden on passing subscriber related parameters (mode, reliability, etc). That's the reason I suggest init/config initialization to make things simple.

**Comment by OlivierHecart** [comment]
The burden of having zenoh entities lifetimes bound to the session lifetime when writing multitask apps is something that comes back again and again from users. So I decided to tacle it. I introduced a new leak() function that allows to get a static session reference and so easily move entities and subscribers in threads or tasks. Here is an example on how to use it : 
https://github.com/eclipse-zenoh/zenoh/blob/852f2511f68bd3aabc410bd8da683d436e324f6a/zenoh/src/session.rs#L257
This solution has drawbacks but was very quick to introduced. We discussed a more advanced solution based on Arc similar to what you suggest. But I'm not sure when this will get in.

I'm not particularly fan of the subscriber.receiver() indirection either. I can't recall all the reasons why I ended up doing it like this but the main reason is that while the subscriber is not clonable and has a lifetime bound to the session's one, the receiver don't have those limitations. So cloning and moving the receiver was an easy way of receiving samples in different tasks until now. If we decide to tacle the multitask problem more directly, maybe this will not be as useful any more and we may want to remove this indirection indeed.

**Comment by OlivierHecart** [comment]
The API has been improved to facilitate the use of Arc<Session>, the creation of 'static Subscribers and Queryables and the use of zenoh in multithread environments in general. Here is an example : https://github.com/eclipse-zenoh/zenoh/blob/b1dfb4e1fb41b012194f5613d8e0703b6af09214/zenoh/src/session.rs#L281 .

A publish() function has been added to the zenoh Session that returns a Publisher which implements the Sink trait. This makes direct forwarding easy. Example : https://github.com/eclipse-zenoh/zenoh/blob/b1dfb4e1fb41b012194f5613d8e0703b6af09214/zenoh/examples/z_forward.rs#L18 .

Subscribers and Queryables implement the Stream and Receiver traits which makes the receiver() indirection optional.
