### ISSUE TITLE
File descriptor leak on 0.5.0-beta.9

### ISSUE THREAD

**Issue by jerry73204** [eclipse-zenoh/zenoh#165]
Recently I work on measuring the message loss rate under distinct # of peers and payload size configurations.
The benchmark code runs Zenoh sessions for each peer, performs message exchange and closes sessions respectively. It repeats the steps for each configuration. It eventually panics on reaching file descriptor limit after roughly 15 rounds. The code can be found in the gist.

https://gist.github.com/jerry73204/64c8fb79a434a1e152b6b6ab61396629

I watch the process using htop + lsof. It shows apparent file descriptor leak by observing that the # of open shmem and sockets does not decrease after each `zenoh.close()`. I attempted to read the source. AFAIK, the `shm.rs` looks innocent. The RUST\_LOG shows that the `Runtime` and `Session` actually calls the `close()`. I see nowhere owning the shared memory could leak in `Arc` or in a spawned infinite loop so far. Perhaps some resources are owned by a singleton or whatever?

**Comment by Mallets** [comment]
Hi @jerry73204 , thanks for pointing this out.

Can you please provide more info on your testing platform? 

I stumbled upon this same problem in the past and I backtraced the behaviour in zenoh and I ended up with the same conclusion as you. There no singleton in zenoh holding those reference. My feeling is that the shared memory library we are using doesn't release properly those file descriptors yielding a leak.

What's your feeling about this?

**Comment by jerry73204** [comment]
It was tested on my Arch Linux laptop with i7-10750H CPU w/ 12 hyperthreads.

I read the `Shmem` source and see the drop code is carefully designed ([link](https://github.com/elast0ny/shared_memory/blob/5474dd5bf95949a1e9922f817cc3ce03d32b539c/src/unix.rs#L28-L63)).  The fd is always closed if not zero. I see no chance that fd could leak. BTW, the lsof shows that it's not only leaking shmem files, but also IPv4 sockets. Things are worse than that.

**Comment by Mallets** [comment]
Can you try one of zenoh tests and check if you see the leaks?

```sh
cargo test transport_unicast_tcp_only -- --nocapture
```

And a more aggressive test in terms of socket open/close:

```sh
cargo test transport_tcp_intermittent -- --nocapture
```

**Comment by jerry73204** [comment]
Both tests look normal to me, too.

Did you run the gist code and see any findings? I monitor the open files in htop. (Press 'l' to list open files for that process, and press F5 to refresh) Both the # of sockets and shmem files increase over time.

**Comment by Mallets** [comment]
So, I run your gist code and I found the leaks due to non-proper cleanup of zenoh runtime.
I fixed that in my [fork](https://github.com/Mallets/zenoh) (synched with master, so 0.6.0), tests are still running.
Once completed, I'll do a PR to the [zenoh official repo](https://github.com/eclipse-zenoh/zenoh).

I modified accordingly your code to run with 0.6.0 APIs.
Please find the code here: [https://gist.github.com/Mallets/3ef4f07bbb3839bcff343315a3224e3d](https://gist.github.com/Mallets/3ef4f07bbb3839bcff343315a3224e3d)

I didn't notice any further leak, could you please confirm that?

**Comment by jerry73204** [comment]
Thanks. I can confirm that it effectively fixes the fd leak. BTW, I ran the test in the long-term and noticed huge memory growth up to 10GB. The htop shows increasing value in RES column and constant SHR memory usage. The `/proc/xxx/maps` suggests that it's allocating a lot of heap.

**Comment by Mallets** [comment]
Great for the confirmation. I'm closing this issue then.
For the memory consumption, I suggest to open a new issue.
