### ISSUE TITLE
Renaming the `storages` plugin's "backends"' and "storages"

### ISSUE THREAD

**Issue by p-avital** [eclipse-zenoh/zenoh#220]
@sreeja and I were discussing that the "backends" and "storages" part of the config are unintuitive (and possibly misleading to some), as "backend" is typically the lowest part of the foodchain, and "storages" is both the largest and smallest configuration unit for the `storages` plugin in configuration files.

Before we release 0.6.0, it'd be good to rename them to avoid semantic collisions. Here are two proposals we have thought of:
- Our favourite would be replacing "backends" with "warehouses" and "storages" with "shelves". This is skeuomorphic and should thus be easily understandable by the largest number. It conveys the scale of each level better and lets us distinguish a warehouse from the backend it's actually running on.
- More "serioussy" but less expressive, "backends" could become "connectors", and "storages" could become "stores" to help distinguish them from the "storages" plugin. This at least removes the homonymous part of the configuration, and reduces the over-genericity of "backends"

Pinging @kydos @JEnoch @OlivierHecart @Mallets @gabrik @J-Loudet @cguimaraes

**Comment by p-avital** [comment]
Just to get a poll running:
- in favor of keeping `storages/backends/<name>/storages/<name>`

**Comment by p-avital** [comment]
- in favor of switching to `storages/warehouses/<name>/shelves/<name>`

**Comment by p-avital** [comment]
- in favor of switching to `storages/connectors/<name>/stores/<name>`

**Comment by JEnoch** [comment]
I agree that having twice `storages` in the configuration path is confusing.

My thought wrt. the proposals:
 - since the very beginning (YAKS) zenoh is (also) about Key/Value **Store** and Geo-Distributed **Storages**.
    I don't think we can avoid 1 of those 2 names. Using synonyms as *"warehouse"* or *"shelve"* brings more confusion in my opinion.
 - still, using both names (`storages` and `store`) might make the user wonder: "what's the difference ?"
 - `backend` might not be a clear name. However it's now used in the repositories names. Changing it is feasible but has a significant impact. 
 - I agree `connector` is a nice name wrt. databases. But user might also wonder why the plugins for DDS, MQTT... are not also `connectors`. I feel `backend` more related to `storages` in that sense.

My proposal is rather to keep `backend` and `storages` but to fins another name for the plugin that manages (i.e. load/create/deletes) those concepts. 
The "simplest" would be: `storage_mgt/backends/<name>/storages/<name>`
But I'm open to other suggestions.

**Comment by p-avital** [comment]
@OlivierHecart and I debated Friday evening and also agreed that renaming the `storages` plugin would probably be better than renaming the `storages` field.

The word I really want to kill is `backend`, it's only reason for being there in the first place is that "it's a plugin for a plugin, but we didn't want to say plugin twice". Arguably with the renaming of the plugin, it could be a bit less obtuse, as it becomes a "storage management backend", which at least sounds more like valid english than "storage backend". I still don't like that "backend" is:
- very implementation detail-y
- misses an indirection, as "backend" refers more to the storage technology than to a configuration of one (since the same backend can be loaded multiple times, to configure multiple influxdb backends for example).

Removing "backend" from the configuration terminology doesn't necessarily mean we have to remove it from the development terminology: each backend crate does indeed define a single technological backend.

Another option @OlivierHecart and I started converging towards last Friday would be "volume" instead of "backend" or "connector". It may be better still, as "connector" has non-storage lexical connections that "volume" doesn't.

**Comment by p-avital** [comment]
New poll entry, feel free to switch your votes:
- `storages` plugin becomes `storage_manager`, `backends` becomes `volumes` in configuration (the crates are still backends, specifically storage-management-backends) and `storages` remain

**Comment by JEnoch** [comment]
I don't like the inflation of names/concepts. It's already complex enough with 3 (plugin, backend, storage). I think adding one (volume) will increase the confusion.

If we consider the backend as implementation detail, we could also make it a configuration detail for the storage and remove this level. e.g.:
```json5
{
  plugins: {
    storages: {
      demo: {
        key_expr: "/demo/example/**",
        db: "zenoh_example",
        create_db: true,
        backend: {
           name: "influxdb",
           url: "http://localhost:8086"
        },
      demo2: {
        key_expr: "/demo2/example/**",
        db: "zenoh_example2",
        create_db: true,
        backend: {
           name: "influxdb",
           url: "http://localhost:8086"
        },
      demo_mem: {
        key_expr: "/demo_mem/example/**",
        db: "zenoh_example2",
        backend: {
           name: "memory",
        }
      }
    }
  }
}
```

The only drawback would be redundancy of backend conf in case several storages are using the same one.

**Comment by p-avital** [comment]
I don't want to add, `backend` is a dev concept, and shouldn't appear at all in configuration. Using `backend` in configuration is the same sort of shortcut as referring to `partitions` as `hard drives` because a common case is that each drive only provides one user-facing partition.

People who care about the `backend` concept and the `volume` concept are different kinds of public. Developpers care about (and are familiar with) backends, administrators care about instances of backends, ie. volumes/connectors. Conflating these two concepts by refering to them with a single word only masks the issue that they are two different things, just like objects and their classes.

Treating backends as implementation details makes sense conceptually, but it's got a lot of drawbacks:
- Two-step configuration (volume/backend first, then storage) becomes impossible, unless we allow storages to be defined before their backend is specified. This would bring its own set of problems, as debuging that a storage you defined isn't running because you haven't added a backend for it yet would definitely not be trivial to users that haven't dealt with that specific issue before. Just to be clear, I think storage-then-backend 2-step-config is a horrible idea that would lead to a lot of hard-to-debug configuration issues.
- It's uncomfortable, as config-hungry backends will have to be repeated any time you want to create a storage. In the case of hand-written configuration requests through `curl`, maintaining proper serialization grows harder as the depth of said configuration becomes greater due to the previous point. If you want an example of that, you example has borked JSON5 (:p), and the only reason I spotted it was using it as a base for the example coming up later.
- Mutualiasing backends is no-longer trivial from the user's perspective: in your example, spawning a single instance of the influxdb backend would suffice, and we could implement that by checking for strict equality between `backend` fields; but that mutualisation behavior is obvious with the current scheme, and wouldn't be with the reverse one.

Another approach that I just realized is an option would be:
```javascript
plugins: {
  storage_manager: {
    volumes: {
      influxdb: {url: "http://localhost:8086"},
      "influxdb-the-second": {
         __path__: ["/path/to/libz_backendinfluxdb.so"],
         url: "http://localhost:8087"
      }
      "influxdb-the-third": {
         __backend__: "influxdb" // by splitting backend and volume, writing this becomes somewhat natural for multiple instances of the same backend
         url: "http://localhost:8087"
      }
    },
    storages: {
      demo: {
        key_expr: "/demo/example/**",
        db: "zenoh_example",
        create_db: true,
        volume: "influxdb",
      },
      demo2: {
        key_expr: "/demo2/example/**",
        db: "zenoh_example2",
        create_db: true,
        volume: "influxdb",
      },
      demo_mem: {
        key_expr: "/demo_mem/example/**",
        volume: "memory" // the "memory" volume always exists
      },
      demo_3: {
        key_expr: "/demo_3/example/**",
        db: "zenoh_example",
        create_db: true,
        volume: "influxdb-the-second"
      }
    }
  }
}
```

**Comment by JEnoch** [comment]
After direct discussion with @p-avital, we concluded that:

1. It's better to introduce the distinction between the `backend` which is the concrete library/implementation, and the `volume` which is a configurable instance of a backend (and a *"factory"* for storages).
2. In the configuration, a hierarchical organisation of `volumes` and `storages` allows the creation of a volume+storage with a single `curl` command. While separate config for each doesn't allow this.

Thus, our new joint-proposal for the configuration hierarchy is the following:
 `storage_manager/volumes/<name>/storages/<name>`

Impacts:
 - change the storages plugin's configuration to introduce `volumes` and the optional `__backend__` attribute (if not specified, the volume must have the same name than the backend)
 - rename the library `zplugin_storages` into `zplugin_storage_manager`
 - rename the crate `zenoh-plugin-storages` into `zenoh-plugin-storage-manager` (for coherency)
 - docs/slides update...

@kydos , @Mallets , @sreeja, @OlivierHecart : please agree or veto !

**Comment by p-avital** [comment]
Just to inform the community on what  these debates led to:

## Distinguishing `backends` and `volumes`:
`volumes` are to `backends` what `objects` (or instances) are to `classes`. From now on, we will do our best to stick to this new terminology, which we hope will create more clarity than confusion.

## Separating `volumes` and `storages` in structured configuration:
Up till now, `storages` were a property of their containing `volumes`. While this made sense to avoid repeating information, this lacks flexibility, and would make access-control less intuitive (when we will handle access-control) to allow some users to create new storages but not new volumes.

The configuration will follow the pattern proposed in [this comment](https://github.com/eclipse-zenoh/zenoh/issues/220#issuecomment-1066776709) by release 0.6.0. In the future, this new indirection will also allow us to get closer to the original vision of storages, where users could specify `requirements`, which the storage manager would then use to select the most appropriate `volume` available.
