### ISSUE TITLE
Performance regression with a zenoh-pico subscriber

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh#250]
It seems that commit https://github.com/eclipse-zenoh/zenoh/commit/c0d746f54f3f366db2c759116b84eb6825a68252 introduced a performance regression in `zenohd` that affects only zenoh-pico subscriber.

**Comment by william-wyliang** [comment]
After further investigation, we can **narrow down** the issue and find it **started to happen from the commit afa20ff680adfc2524adbadceb84677547bf7d40**.

commit afa20ff680adfc2524adbadceb84677547bf7d40
Date:   Mon Mar 28 09:13:48 2022 +0200

    Transport config rework. Added config support for queue size.

### Here is the summary of the tests.

* Issue: https://github.com/eclipse-zenoh/zenoh/issues/250

* Test Conditions:
    zenoh-pico <--> zenohd <--> zenoh-rust
    payload: 8bytes
    priority setting: run with "sudo nice -n -10"
    machine: single laptop with i7-1165G7, 16GB DRAM

* Commit Logs for the reported commit c0d746f54f3f366db2c759116b84eb6825a68252
    Merge: ac36c205 10e59b3d
    Date:   Mon Mar 28 14:28:35 2022 +0200
  
        Merge pull request #229 from Mallets/queue_conf
      
        Add configuration support for the TX queue

* A graph view around the commit c0d746f54f3f366db2c759116b84eb6825a68252:

    \* df3a6786 fix --cfg behaviour being broken with commas
    \*   c0d746f5 Merge pull request #229 from Mallets/queue_conf
    |\  
    | * 10e59b3d Fix cargo clippy
    | * afa20ff6 Transport config rework. Added config support for queue size.
    \* | ac36c205 Move version log to Runtime for benefit of plugins
    |/  
    \*   270422c3 Merge pull request #228 from Mallets/rx_buffer

* No problem BEFORE the following commits
  zenoh: ac36c2050af528e94430ec4967cb0a28888e661b
  
    publisher: z_pub_thr
    subscriber: **zn_sub_thr**
    
    **2034381.169030 msgs/sec
    2087237.621299 msgs/sec
    2113627.728141 msgs/sec
    2063212.159969 msgs/sec
    2133745.739431 msgs/sec**
    
    publisher: zn_pub_thr 
    subscriber: z_sub_thr
    
    516491.9468239932 msg/s
    502750.18427805253 msg/s
    499899.5251944312 msg/s
    504607.64812618744 msg/s
    500330.4657709894 msg/s
    
    (extra test: peers mode with pure zenoh-rust)
    publisher: z_pub_thr 
    subscriber: z_sub_thr
    
    2793982.332029205 msg/s
    2823724.1623591697 msg/s
    2802070.2479571574 msg/s
    2852500.1279346305 msg/s
    2873390.319559507 msg/s

* Problem occurs AFTER the following commits
  zenoh: afa20ff680adfc2524adbadceb84677547bf7d40
    
    publisher: z_pub_thr
    subscriber: **zn_sub_thr**
    
    **1355362.243909 msgs/sec
    1543589.819081 msgs/sec
    1423264.652388 msgs/sec
    1265166.112656 msgs/sec
    1473122.554632 msgs/sec**
    
    publisher: zn_pub_thr 
    subscriber: z_sub_thr
    
    483320.0452542225 msg/s
    475029.32130361476 msg/s
    456779.5988600846 msg/s
    529262.2509219735 msg/s
    525274.4853339582 msg/s
    
    (extra test: peers mode with pure zenoh-rust)
    publisher: z_pub_thr 
    subscriber: z_sub_thr
    
    2852441.05630228 msg/s
    2893796.7617661846 msg/s
    2884421.7400712576 msg/s
    2851708.8851235555 msg/s
    2830214.418176407 msg/s
    
    Similar results also observed on:
    zenoh: 10e59b3d20ff5a7e98067af415e0f330a4f80f61
    zenoh: c0d746f54f3f366db2c759116b84eb6825a68252
    More tests can be found [here](https://gist.github.com/william-wyliang/bb8982ceca9a1cdf076488a2aea7377a)
