### ISSUE TITLE
Updating Eclipse Zenoh logo on Github

### ISSUE THREAD

**Issue by hassanjaber98** [eclipse-zenoh/zenoh#281]
### Describe the bug

Link:https://github.com/eclipse-zenoh
New logo:
![image](https://user-images.githubusercontent.com/80693303/172691499-d0ec9835-6501-4e3a-865b-8b2465b58275.png)

### To reproduce

Link:https://github.com/eclipse-zenoh

### System info

Link:https://github.com/eclipse-zenoh

**Comment by JEnoch** [comment]
Unfortunately we don't have the administration privileges to update the logo for the Github **eclipse-zenoh** organization.
Only the Eclipse Foundation can administrate the organization. The issue must be raised on Eclipse's bugzilla.
