### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh#39]
Create a suite of performance tests for zenoh

**Comment by Mallets** [comment]
An initial set of tests is being developed here: [https://github.com/atolab/zenoh-perf](https://github.com/atolab/zenoh-perf).
The final goal is to integrate those performance tests in the main zenoh repository.

**Comment by Mallets** [comment]
Closing the issue. 

An announcement will be made when the suite will be integrated in the main repo. For the time being, please refer to the repo here: [https://github.com/atolab/zenoh-perf](https://github.com/atolab/zenoh-perf).
