### ISSUE TITLE
Use clap 4.x.x for CLI argument parsing

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh#391]
### Describe the feature

Currently Zenoh uses clap 3.x.x to handle CLI argument parsing.
Clap 4.x.x has been released and it introduces some API changes.

It would be great if Zenoh will:
- move to Clap 4.x.x to keep up-to-date with its dependencies
- make use os [Clap structopt](https://docs.rs/clap/latest/clap/#example) to reduce boilerplate in the examples

**Comment by 0xkelvin** [comment]
i will work on this @Mallets

**Comment by Mallets** [comment]
> i will work on this @Mallets

Great! Thanks for volunteering. I've assigned to you this issue. 
Looking forward for the PR!

FYI: We will need you to sign the [Eclipse ECA](https://www.eclipse.org/legal/ECA.php) (if you haven't done it yet) in order to accept your PR. This is a requirement from Eclipse and the CI will spot that at the time of submitting the PR. No need to do it now though.

**Comment by 0xkelvin** [comment]
hi @Mallets , i still working on this, was busy last week

**Comment by gautamprikshit1** [comment]
@0xkelvin Are you still working on this or Shall I take it? Thanks

**Comment by 0xkelvin** [comment]
> @0xkelvin Are you still working on this or Shall I take it? Thanks

hello, i still working on this, planing for PR by end of this week
