### ISSUE TITLE
Examples on windows doesn't see each other [Bug] 

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#408]
### Describe the bug

On windows examples doesn't communicate to each other. Issue copied from zenoh-c, as it's actuallly main zenoh problem - https://github.com/eclipse-zenoh/zenoh-c/issues/119

### To reproduce

Compile examples on windows and run `z_queryable` and `z_get`. `z_get` receives nothing. Also `z_info` doesn't show peers other than itself

### System info

- Windows 11 Pro 22H2
- AMD Ryzen 7

**Comment by Mallets** [comment]
Is there any log showing that listening on IPv6 has failed? 

I wouldn't move peers by default back to IPv4, it's especially between peers where having IPv6 make more sense. If opening a listen on IPv6 returns an error, we could try to fallback on IPv4.

**Comment by OlivierHecart** [comment]
To clarify my point: 
I don't think either that we should move peers by default back to IPv4. I'm just stating that until we properly fix this issue users can workaround the issue by explicitly setting listening endpoints to `tcp/0.0.0.0:0` and `tcp/0.0.0.0:7447` on windows.
