### ISSUE TITLE
C++ API

### ISSUE THREAD

**Issue by nbanal** [eclipse-zenoh/zenoh#44]
Looks like https://docs.rs/cxx/0.4.7/cxx/ would be a good approach in terms of safety and performance to call Rust code from C++.

@kydos Could you define the C++ APIs that we need?

**Comment by kydos** [comment]
@nbanal the cxx crate seems definitively the right approach. For what concerns the API I'd like to start with zenoh-net and see something that looks as close as possible to the Rust API.

**Comment by nbanal** [comment]
@kydos 

Once this feature is implemented, what would be the workflow from user's perspective?  I can imagine something like that:

1. Define the interfaces implemented in Rust (the `zenoh-net` APIs) and in C++ (nothing) inside an `ffi module`
1. Build `zenoh-net` with Cargo as a lib
1. Create an application in C++ that links the previously built library
1. Run the C++ executable

Are the steps above correct?

**Comment by kydos** [comment]
Hello @nbanal, 

From a user perspective, once installed the zenoh-cxx dependency, the user should just include "zenoh.hpp" code, compile, link and run. This is the same workflow we have for zenoh-c.

Beside, now that zenoh-pico is out, what may make sense is to have the C++ API done straight on zenoh-c and zenoh-pico.

**Comment by Mallets** [comment]
A Zenoh C++ API is now available here: https://github.com/eclipse-zenoh/zenoh-cpp
