### ISSUE TITLE
zero-copy

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh#46]
Ideally we would want to avoid any copy when sending large data, such as images or point clouds, or anything else sufficiently big. 

zenoh should provide a way to allocate and manage shared memory buffers and transparently transfer them using zero-copy to subscribers on the same node while streaming the content over sockets for subscribers across the network.

All of this should be as transparent as possible to the users and the memory management for the shared-memory buffers should  follow Rust ownership (as much as possible).

**Comment by kydos** [comment]
We jave just committed initial support for zero-copy. The next step will be to ensure that remote applications (those across the network) are delivered with the entire content as opposed to the context information necessary to access the shared memory buffer. For the time being we have decided not to include RDMA as part of this issue, that said, that framework we've put in place should easily extend to support RDMA.

**Comment by Mallets** [comment]
Commit [543eacd1dbd8d2ffb63238ccf0068b83b402f35e](https://github.com/eclipse-zenoh/zenoh/commit/543eacd1dbd8d2ffb63238ccf0068b83b402f35e) solves this issue. Closing.
