### ISSUE TITLE
zenoh-pico

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh#51]
Make available a zenoh C client library for micro-controllers.

**Comment by Mallets** [comment]
A zenoh C client library for micro-controllers is now available as [zenoh-pico](https://github.com/eclipse-zenoh/zenoh-pico). A tagged version (0.5.0-beta.5) exists matching the current zenoh 0.5.0-beta.5 protocol implementation. 

Deb, rpm, and tgz packages are provided for the following targes: linux-armv5 linux-armv6 linux-armv7 linux-armv7a linux-arm64 linux-mips linux-x86 linux-x64. They can be downloaded from the [Eclipse zenoh-pico download area](https://download.eclipse.org/zenoh/zenoh-pico/ ).
