### ISSUE TITLE
mTLS option to ignore domainNames

### ISSUE THREAD

**Issue by Fritiofhedstrom** [eclipse-zenoh/zenoh#513]
### Describe the feature

I am using Zenoh mTLS in a local network and  I am not interested in verifying the domain names of servers, I am using the CA as a "network certificate", if it's is signed by the CA, then it should be allowed in the zenoh network. Using the IpAdress domain name feature from last release is useful, but I can't guarantee that my Ip adress does not change. I feel like the best solution would be to not verify domain names at all for my zenoh network. 

I belive this can be implemented in two ways, either implementing the ServerCertVerifier on a zenoh struct and using that, or adding another verifier in rustls and updating the dependencies to use that one. 
I would prefer adding it to rustls because that means that a lot of code can be used from the default verifier WebPkiVerifier.

 I will be making a PR to rustls and depending on how that goes I will make the appropriate updates to this issue

**Comment by Mallets** [comment]
@Fritiofhedstrom I've seen https://github.com/rustls/rustls/pull/1325 has been merged. That means the proper configuration should be now added to Zenoh?

**Comment by Fritiofhedstrom** [comment]
Yes I have been doing some other stuff, but I have a local branch, I can make a PR soon

**Comment by Mallets** [comment]
Closed by #527
