### ISSUE TITLE
[Bug] systemd error 217/user on fresh install

### ISSUE THREAD

**Issue by eliasdc** [eclipse-zenoh/zenoh#515]
### Describe the bug

Zenohd systemd fails to launch from a fresh install of `zenohd`.

post installation step on debian fails to recognize `systemctl` with the test `command -v systemctl` in `zenoh/zenohd/.deb/postinst`, which then skips adding the zenohd user which is used to launch the service.

Bug introduced in tagged version [0.7.2-dev] and from commit 6beb99c

### To reproduce

1. apt purge zenoh*
2. apt install zenohd
3. systemctl start zenohd.service
4. systemctl status zenohd.service

### System info

- Platform: [Ubuntu 20.04 64-bit, Ubuntu 22.04 64-bit]
- Zenohd version [0.7.2-rc]
- Bug introduced in [0.7.2-dev]

**Comment by Mallets** [comment]
@evshary was this issue solved or is it still open?

**Comment by evshary** [comment]
> @evshary was this issue solved or is it still open?

This should be solved after that bugfix.

**Comment by Mallets** [comment]
Closing the issue then, if the problem still persist let's reopen it.
