### ISSUE TITLE
Replacement of `#` separator for fragments in the Selector

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh#53]
# Rational
We need to replace the usage of `#` as separator for fragments in Selector because most of the web client won't send the fragment part of the URL to the zenoh HTTP plugin.

# Detail
The current (in 0.5.0-beta.5) specification of a zenoh Selector is the following:
```text
/s1/s2/.../sn?x>1&y<2&...&z=4(p1=v1;p2=v2;...;pn=vn)#a;b;x;y;...;z
|           | |             | |                   |  |           |
|-- expr ---| |--- filter --| |---- properties ---|  |--fragment-|
```
where:
 * __expr__: is a Path Expression (e.g.: `/demo/example/**`)
 * __filter__: a list of predicates separated by `'&'` allowing to perform filtering on the values
   associated with the matching keys. Each predicate has the form "`field`-`operator`-`value`" value where:
     * _field_ is the name of a field in the value (is applicable and is existing. otherwise the predicate is false)
     * _operator_ is one of a comparison operators: `<` , `>` , `<=` , `>=` , `=` , `!=`
     * _value_ is the the value to compare the field’s value with
 * __fragment__: a list of fields names allowing to return a sub-part of each value. A.k.a. a __projection__ in the mathematical sense of the term.
   This feature only applies to structured values using a “self-describing” encoding, such as JSON or XML.
   It allows to select only some fields within the structure. A new structure with only the selected fields
   will be used in place of the original value.

For instance, if we imagine GPS coordinates of objects stored zenoh's time-series storages, under an undetermined hierarchy prefixed by `/demo/example/`, this Selector:
`/demo/examples/**/GPS-coordinate?lat>0(starttime=now()-1h)#lat;long;name`
will retrieve all the GPS data of objects in the north hemisphere (lat>0) within the last hour (starttime=now()-1h) and for each  data only the latitude, the longitude and the name should be returned.

A Selector can easily be used to get path/values from zenoh via the HTTP plugin, simply prepending the selector with the base URL of a zenoh router. E.g.:
`http://localhost:8000/demo/examples/**/GPS-coordinate?lat>0(starttime=now()-1h)#lat;long;name`
However, the majority of HTTP clients (web browsers, curl...) never send the fragment part of the URL (starting from `#`) to the web server (the zenoh HTTP plugin in our case). As a consequence, a web client won't be able to request only sub-parts of data.

**Comment by JEnoch** [comment]
For coherency with the zenoh API where the Selector is the only parameter used in a `get()` operation, we want to keep the expression of the projection within the Selector. And within in the URL for HTTP (not in a HTTP header). 

The only parts from the [URL](https://en.wikipedia.org/wiki/URL) that are sent by a web client to the server are the scheme, the authority, the path and the query. As the URL's path correspond to the Selector's path expression, only the query can be used for the projection. And we need to distinguish it from the filter and properties parts.

Considering the [RFC-3986 section on URI reserved characters](https://tools.ietf.org/html/rfc3986#section-2.2):
```text
      reserved    = gen-delims / sub-delims
      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
```
_"The purpose of reserved characters is to provide a set of delimiting characters that are distinguishable from other data within a URI."_
...
_"Thus, characters in the reserved set are protected from normalization and are therefore safe to be used by scheme-specific and producer-specific algorithms for delimiting data subcomponents within a URI."_
I think one (or 2) of those reserved character shall be used.

Proposals distinguish the projection part within the query part:
 * `[ ]` surrounded.
   * pros: similar to `( )` surrounding the properties
   * cons: we could consider to use those in filter to test the nth value of a list. E.g.: `/demo/example/**?my_list[0]>1`
 * `@` as separator.
   * pros: unlikely to be used in filter or properties. But should be percent-encoded (%40) if so.
   * cons: weird...?
 * `$` as separator.
   * cons: we could consider to use it for placeholders (similar to env variable). E.g.: `/demo/example/**?x>$LIMIT` where the value of $LIMIT could be retrieved from a specific path in zenoh (e.g. `/env/LIMIT`)

**Comment by JEnoch** [comment]
@kydos, @OlivierHecart , @Mallets 
My vote goes for `[ ]`. But feel free to give your opinion and/or make other suggestions.

**Comment by heyong4725** [comment]
My vote goes for [ ] as well:)

**Comment by kydos** [comment]
+1

**Comment by Mallets** [comment]
+1 for [ ]
