### ISSUE TITLE
Added image format bmp

### ISSUE THREAD

**Issue by sanri** [eclipse-zenoh/zenoh#535]
### Describe the feature

In KnownEncoding enumeration, add the enumeration ImageBmp.
```rust
pub enum KnownEncoding { 
    Empty = 0,
    AppOctetStream = 1,
    AppCustom = 2,
    TextPlain = 3,
    AppProperties = 4,
    AppJson = 5,
    AppSql = 6,
    AppInteger = 7,
    AppFloat = 8,
    AppXml = 9,
    AppXhtmlXml = 10,
    AppXWwwFormUrlencoded = 11,
    TextJson = 12,
    TextHtml = 13,
    TextXml = 14,
    TextCss = 15,
    TextCsv = 16,
    TextJavascript = 17,
    ImageJpeg = 18,
    ImagePng = 19,
    ImageGif = 20,
    ImageBmp = 21,    // hope to increase
}
```

**Comment by YuanYuYuan** [comment]
Hi @sanri , thanks for your suggestion. Since the change of this would affect the binding in other languages, like zenoh-python, zeonoh-c, zenoh-pico, etc. We're still seeking a proper way to make it easily extensible.

**Comment by sanri** [comment]
Hi @YuanYuYuan. 
Hope to facilitate the development of tools as the goal of design.
The data is divided into several large types, numbers, text, pictures, binary data blocks...
Under each large type, add common subtypes and reserve custom type fields.

For example, picture data, commonly used picture data formats have their own type markers, which can generally be uniformly processed.

**Comment by p-avital** [comment]
`Encoding` already works as a prefix+suffix, so this would only require adding `application/`, `text/`, `image/` to the enum to get a bit of compression in (the rest of the encoding will be sent as a string).

Since we're a bit tied up with major works for the next release ATM, I'd really love it if you decided to take it upon yourself to both:
- add said prefixes to the `KnownEncoding` enum, this will also require some changes in other sections of the code so that Zenoh knows what to decompress it to.
- add these variants to the bindings (zenoh-python, zenoh-c, zenoh-cpp should just be re-exporting zenoh-c's, so probably no change there...), as well as zenoh-pico.

If you feel that's too much work, then let us know and we'll just add it to our backlog :)

**Comment by sanri** [comment]
So, KnownEncoding changed to this?

```rust
pub enum KnownEncoding { 
    Empty = 0,
    AppOctetStream = 1,
    AppCustom = 2,
    TextPlain = 3,
    AppProperties = 4,
    AppJson = 5,
    AppSql = 6,
    AppInteger = 7,
    AppFloat = 8,
    AppXml = 9,
    AppXhtmlXml = 10,
    AppXWwwFormUrlencoded = 11,
    TextJson = 12,
    TextHtml = 13,
    TextXml = 14,
    TextCss = 15,
    TextCsv = 16,
    TextJavascript = 17,
    ImageJpeg = 18,
    ImagePng = 19,
    ImageGif = 20,
    Image = 21,    // new
    Text = 22,     // new
    App = 23,      // new
}
```

**Comment by sanri** [comment]
I can modify zenoh, zenoh-c, zenoh-cpp, from which branch to create a feature branch?

I haven't seen the zenoh-python and zenoh-pico code yet, so if I try it, it might be slow.

**Comment by p-avital** [comment]
You should probably branch from master on all repos :) 

(BTW, if you're not used to it, I advise always branching when preparing a PR. If you do a PR from `your-repo/master` to `eclipse-zenoh/master`, it's gonna be harder for you to merge our master into your own if needed)

Fortunately, the `KnownEncoding` code isn't really complex, it's just time consuming to work with. In general, just searching globally for it in all repos should be sufficient to find all the spots of interest, and they shouldn't be too numerous in the bindings.

**Comment by sanri** [comment]
I have tested two ways of sending image data after compression encoding and sending it directly. (The image has 20 million pixels, about 20MB)

It is found that the bandwidth resources saved and the cpu time occupied by the compressed transmission are not cost-effective. So send the raw image data directly.
When sending raw data, we must use Encoding::WithSuffix and add other meta information.

**Comment by sanri** [comment]
Withdraw this offer
