### ISSUE TITLE
Using zenoh in multiple threads

### ISSUE THREAD

**Issue by MHOOO** [eclipse-zenoh/zenoh#59]
I'm wondering how that would be possible. `Workspace` holds a `Zenoh` instance, so just locking `Zenoh` with a `Mutex` (e.g. the tokio one, which is `Send`able) would not be safe. Is this even supported to begin with or am I just using the library wrong?

Ideally I would like to just get a bunch of `ChangeStreams` and use those around in my application, but how can I pass them around, when they require a `Workspace` instance with a longer lifetime?

**Comment by gabrik** [comment]
Hi @MHOOO,

Ideally, you should not pass the `Workspace` around tasks but instead, wrap the `Zenoh` instance inside an `Arc`, then from that one, you can recover the `Workspace` when needed. 

This is the way we use it in [fog05](https://github.com/eclipse-fog05/fog05) as we also like to leverage on multiple tasks.

For example in our `agent` we have [this code](https://github.com/eclipse-fog05/fog05/blob/master/fog05-agent/src/main.rs#L132) that is used to create the `Arc<Zenoh>` and then we just clone, sharing the same session among multiple tasks.


Regarding passing the `ChangeStream` I would have the subscriber in one task, getting data from the `ChangeStream` and then pass this data to other tasks by the means of `Channels` or `Vec<T>`, eventually using `Arc` or `RwLock` in case of the `Vec` to allow multiple tasks to read/write.

I hope this clarifies how to share the `Zenoh` across tasks/threads.

**Comment by MHOOO** [comment]
Hi @gabrik,

the fog05 Codebase certainly helps, thanks for pointing me there. I just wonder why no `Mutex<Zenoh>` ist required, but I guess zenoh does internal locking.

**Comment by JEnoch** [comment]
Hi @MHOOO 

> I just wonder why no Mutex<Zenoh> ist required, but I guess zenoh does internal locking.

Yes it does: the [Zenoh](https://github.com/eclipse-zenoh/zenoh/blob/0db64d8265b4e294fee977e9e5e7e68b8c924739/zenoh/src/lib.rs#L119) instance owns a zenoh-net [Session](https://github.com/eclipse-zenoh/zenoh/blob/0db64d8265b4e294fee977e9e5e7e68b8c924739/zenoh/src/net/session.rs#L179) which owns 2 internal states (SessionState and [Runtime::RuntimeState](https://github.com/eclipse-zenoh/zenoh/blob/0db64d8265b4e294fee977e9e5e7e68b8c924739/zenoh-router/src/runtime/mod.rs#L37)) that are each wrapped inside an `Arc<RwLock<T>>`.

**Comment by OlivierHecart** [comment]
Some work has been done to facilitate the use of zenoh in multithread applications as part of issue #162
In particular see comment : https://github.com/eclipse-zenoh/zenoh/issues/162#issuecomment-1015584308
