### ISSUE TITLE
[Bug] Example readme refers to non-existing `z_sub_shm_thr` and documentation seems broken

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-zenoh/zenoh#594]
### Describe the bug

I wanted to play around with the zenoh shared memory example that is described in here: https://github.com/eclipse-zenoh/zenoh/blob/master/examples/README.md

The README mentions the `z_sub_shm_thr` example that is actually missing and the call to `z_pub_shm_thr` does not work like it is described in the readme.

Furthermore, it was not clear to me what kind of exact format an endpoint requires that I have to provide with `listen` or `connect` in `z_pub_shm_thr`. A link to a documentation describing/listing available protocols would be nice and a working command line example that is using these parameters with some meaningful values.

### To reproduce

1. `cargo run --example z_sub_shm_thr`, results in `No example target named 'z_sub_shm_thr'`
2. `cargo run --example z_pub_shm_thr`, requires additional parameters that are not discussed in the example from the readme

### System info

all

**Comment by JEnoch** [comment]
Hi @elfenpiff ,
Thanks for reporting this!

Actually the code doesn't change on subscriber side wrt. shared memory usage.
Thus the `z_sub_thr` example shall be used with both `z_pub_thr` and `z_pub_shm_thr`.

I'm fixing the README in #598, as well as fixing the examples that were not enabling shared-memory usage in their [configuration](https://github.com/eclipse-zenoh/zenoh/blob/8954a81cb55002698b441b94fe777c7955e8bd89/DEFAULT_CONFIG.json5#L234).

> Furthermore, it was not clear to me what kind of exact format an endpoint requires that I have to provide with listen or connect in z_pub_shm_thr. A link to a documentation describing/listing available protocols would be nice and a working command line example that is using these parameters with some meaningful values.

There is no endpoint to configure for shared memory usage.
As part of the Session handshake (whatever the transport - TCP, UDP...), 2 Zenoh applications are automatically negotiating if shared-memory can be used between them (assuming both have the feature enabled, as well as the [configuration](https://github.com/eclipse-zenoh/zenoh/blob/8954a81cb55002698b441b94fe777c7955e8bd89/DEFAULT_CONFIG.json5#L234))

Note that we also recently added in 0.10.0-rc an experimental support of Ultra-Low Latency that can be used with shared-memory:  https://zenoh.io/blog/2023-10-03-zenoh-dragonite/#support-for-ultra-low-latency

**Comment by JEnoch** [comment]
Fixed by #598
