### ISSUE TITLE
Integration tests randomly failing [Bug] 

### ISSUE THREAD

**Issue by yellowhatter** [eclipse-zenoh/zenoh#622]
### Describe the bug

I noticed that some list of our integration tests are randomly failing when executed concurrently on multicore CPU.

That  affects both `master` and `refactor_transport_trait` branches and can be reproduced.

### To reproduce

This sometimes fails:
`cargo nextest run -p zenoh --features unstable`

This doesn't:
`taskset 0x1 cargo nextest run -p zenoh --features unstable`

The failing tests are (that what I noticed):
```
three_node_combination
zenoh_matching_status_any
zenoh_matching_status_remote
zenoh_session_multicast
```

### System info

Ubuntu 22.04
AMD Ryzen 9

**Comment by Mallets** [comment]
While we experienced this kind of flaky tests in the past, it seems this hasn't happened in a while on the CI. 

@yellowhatter Have you observed again such behaviour? Should we keep this issue open?

**Comment by yellowhatter** [comment]
> While we experienced this kind of flaky tests in the past, it seems this hasn't happened in a while on the CI.
> 
> @yellowhatter Have you observed again such behaviour? Should we keep this issue open?

@Mallets no, starting from some undefined point in time I didn't see that anymore. I think we can close this, and I will reopen if I get it again
