### ISSUE TITLE
[Bug] Fragmentation stop working with zenoh-pico

### ISSUE THREAD

**Issue by jean-roland** [eclipse-zenoh/zenoh#629]
### Describe the bug

Trying to send fragmented from zenoh-picoh to a router no longer works as of commit #585 on master.

### To reproduce

1. Start a router: `./target/release/zenohd -l tcp/127.0.0.1:7447 --no-multicast-scouting`
2. Start a zenoh-pico publisher with values >65kB: `rand=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 65536 | head -n 1)
./build/examples/z_pub -e tcp/127.0.0.1:7447 -v $rand`

### System info

- Zenoh version commit 1dc31d47f86396f6817ba34125446d001960de51 and later.

**Comment by Mallets** [comment]
See https://github.com/eclipse-zenoh/zenoh-pico/issues/291 and https://github.com/eclipse-zenoh/zenoh/pull/630

**Comment by Mallets** [comment]
@jean-roland as far as I understand this issues is now solved. Can you please confirm?

**Comment by jean-roland** [comment]
Yes, it has been fixed on the zenoh-pico side. Closing the issue.
