### ISSUE TITLE
[Bug] Unwrap on None value in digest.rs

### ISSUE THREAD

**Issue by chachi** [eclipse-zenoh/zenoh#645]
### Describe the bug

zenohd on v0.10.1-rc crashed due to a panic when unwrapping a None value in `plugins/zenoh-plugin-storage-manager/src/replica/digest.rs:296`

### To reproduce

Only saw this once, so not sure exactly what triggered it.
1. Start zenohd using S3 storage volume and replication enabled.
2. Have another zenohd connect to it and replicate with it.
3. Run a DELETE (we did it via REST plugin)

### System info

- Ubuntu 20.04
- Using docker image for v0.10.1-rc
- S3 storage backend plugin v0.10.1-rc as downloaded from Ecilpse website
- replication enabled and storage has `complete: "true"` enabled

**Comment by Mallets** [comment]
@J-Loudet I think this has already been fixed in `main`. Can you please confirm and close/comment the issue accordingly?
