### ISSUE TITLE
Missing `Session::write`

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh#650]
### Describe the feature

The publisher API contains the following method:

```rs
pub fn write<IntoValue>(&self, kind: SampleKind, value: IntoValue) -> Publication
```

This allows for sending a `Value` with `SampleKind::Delete`. However, the `Session` API has no such method and only offers `Session::delete` which sends an empty buffer.

I would argue it makes little sense to have `write` in `Publisher` but not in `Session`.

**Comment by Mallets** [comment]
The `write` in `Publisher` was added to support `streams` in Rust. I would argue to move the `write` under a specific trait in Rust. This would allow to differentiate an API that is used for enhanced ergonomics in Rust but it may not be available in other bindings.

**Comment by DenisBiryukov91** [comment]
.

**Comment by milyin** [comment]
`Publisher::write` is not a part of "core" zenoh API (https://github.com/eclipse-zenoh/zenoh/blob/tagging/api_core.txt), so we are not too much obliged to keep it fully consistent. As the `Publisher::write` is more like ad-hoc method added for some specific task, it's not necessary to clone it's functionality to `Session`
