### ISSUE TITLE
Missing `no_mangle` feature in `zenoh-plugin-trait` breaks `zenoh-plugin-mqtt`

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh#675]
### Describe the release item

The `sync-lockfiles.yml` workflow currently [fails](https://github.com/eclipse-zenoh/zenoh/actions/runs/7647904502/job/20839719676) with the following error:

```console
error: failed to select a version for `zenoh-plugin-trait`.
    ... required by package `zenoh-plugin-mqtt v0.11.0-dev (/home/runner/work/zenoh/zenoh/zenoh-plugin-mqtt)`
    ... which satisfies path dependency `zenoh-plugin-mqtt` of package `zenoh-bridge-mqtt v0.11.0-dev (/home/runner/work/zenoh/zenoh/zenoh-bridge-mqtt)`
versions that meet the requirements `^0.11.0-dev` are: 0.11.0-dev

the package `zenoh-plugin-mqtt` depends on `zenoh-plugin-trait`, with features: `no_mangle` but `zenoh-plugin-trait` does not have these features.
```

This due to the `no_mangle` feature [removal](https://github.com/eclipse-zenoh/zenoh/pull/583/files#diff-5e75ad7d7ae904692e453728c42eefb0f82713816af4e442b7f0bbd5b138e23e) in #583.

**Comment by milyin** [comment]
Not reproduced anymore. Though two other existing failures in sync-lockfiles were addressed:
https://github.com/eclipse-zenoh/zenoh-plugin-ros1/pull/36
https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/89
