### ISSUE TITLE
Zenoh with default-features=false in the workspace

### ISSUE THREAD

**Issue by yellowhatter** [eclipse-zenoh/zenoh#686]
### Describe the bug

Currently, I see that zenoh is added into our root workspace like this:
(root Cargo.toml)
`zenoh = { version = "0.11.0-dev", path = "zenoh", default-features = false }`

By disabling any default features, we exclude literally ANY link implementations. That affects the default zenoh build and makes the example set not working without customizing it's build.

In order to offer a proper solution, I think we need to discuss why we disabled the default features by default (sounds really weird, right?)

### To reproduce

run any examples with default build
`cargo run --release --package zenoh-examples --example z_pub_shm_thr --features shared-memory -- 8 -e tcp/127.0.0.1:7447 --no-multicast-scouting`

### System info

dosn't really matter

**Comment by Mallets** [comment]
I compile and run examples quite often and I've never experienced this behaviour.
Could you please report the various steps to reproduce it?

**Comment by yellowhatter** [comment]
@Mallets I recently reproduced it with the following command:
`cargo run --release --package zenoh-examples --example z_pub_shm_thr --features shared-memory -- 8 -e tcp/127.0.0.1:7447 --no-multicast-scouting`
used clean recent main branch

**Comment by Mallets** [comment]
Can you retry without passing `--package zenoh-examples`? It should still be able to compile the examples.

**Comment by yellowhatter** [comment]
@Mallets hmm, that worked :) unbelievable...

**Comment by Mallets** [comment]
In any case, the way `cargo features` are propagated in a workspace and included packages is still a bit unclear...

**Comment by yellowhatter** [comment]
Yes, it is really unclear, because workspace=true must take the workspace's zenoh package without any default features.....

Anyway that is quite strange to disable default features by default, isn't it?

**Comment by Mallets** [comment]
It is strange but it's the good way to go to avoid having all features enabled by default in any dependency. Otherwise it would be impossible to disable certain features in transitive dependencies in Zenoh.

**Comment by yellowhatter** [comment]
Ah, ok, I've got the point! Thank you for the explanation
