### ISSUE TITLE
Select endpoint to listen by interface name

### ISSUE THREAD

**Issue by ciandonovan** [eclipse-zenoh/zenoh#691]
### Describe the feature

We use Zenoh over Tailscale (mesh virtual private network) to talk ROS to our robot from anywhere in the world.

We'd like to restrict Zenoh to use only that VPN interface, as it can be quite chatty with multicast and spill over onto the regular unencrypted interfaces if bound to the wildcard 0.0.0.0.

However, the Tailscale IP isn't fixed, so each time that changes the Zenoh config would have to be updated if we wanted to bind only to it.

Ideally, Zenoh could be configured to listen on an IP or set of IPs, given an interface name, similar to what's possible with CycloneDDS.

I expect this will be useful even outside our usecase with Tailscale, such as with other Wireguard/OpenVPNs,  Ethernet-based cellular modems that provide an IP through DHCP, direct WAN attachments, and more.

**Comment by Mallets** [comment]
Transferring the issue to the main Zenoh repository since this change needs to be done in the core of Zenoh. 
Linked to #558.
