### ISSUE TITLE
Memory leaks cleanup

### ISSUE THREAD

**Issue by DenisBiryukov91** [eclipse-zenoh/zenoh#695]
### Describe the release item

There is a series of memory leaks, mostly due to circular dependencies (for example in Runtime) that should be addressed.

**Comment by milyin** [comment]
Just to keep the history of the issue:
Previous attempt to fix is in https://github.com/eclipse-zenoh/zenoh/pull/625
The comments about procedure to find leaks and some tool tooling is in https://github.com/milyin/arc-trace

**Comment by milyin** [comment]
To be resumed after Tokio merging #566
