### ISSUE TITLE
Encoding API rework

### ISSUE THREAD

**Issue by p-avital** [eclipse-zenoh/zenoh#698]
### Describe the release item

The `Encoding` type has been too leaky of an abstraction. For the next release, we plan a breaking change around it, making it closer to how KeyExpr functions, allowing the user to interact more simply with it.

**Comment by p-avital** [comment]
The new API shall abstract encodings as an integer-string pair, reserving a range for the Zenoh Project (size of the range TBD, presumably between 256 and 1024 values) and allowing users to define their own.

No attempt shall be made of shortening encodings passed by the user, nor of decompressing integers to the prefix they correspond to, apart from the REST plugin attempting to decompress in order to expose mime types.

**Comment by milyin** [comment]
The PR https://github.com/eclipse-zenoh/zenoh/pull/764 should close this issue

**Comment by Mallets** [comment]
Closed by #764 which has been merged in https://github.com/eclipse-zenoh/zenoh/tree/protocol_changes.
It will be eventually merged in main.
