### ISSUE TITLE
make sure that important trait methods are easy to find

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#710]
This update https://github.com/eclipse-zenoh/zenoh/pull/688 moves several key functions of `Session` to separate trait. Need to make sure that it's easy to navigate to this functionality in the documentation.
This is a problem in rust autogenerated documentation: methods of structure are considered important and visible immediately, but trait implementations are deep buried in lots of helping traits like `Deref`, `Clone`and `Display`. If this happens, need to make sure that key traits like `SessionDeclarations` are linked from the structure description.

**Comment by Mallets** [comment]
Closed by #1193
