### ISSUE TITLE
`brew install zenoh` failed on M1Mac

### ISSUE THREAD

**Issue by takasehideki** [eclipse-zenoh/zenoh#711]
### Describe the bug

`brew install zenoh` failed on my M1 Mac environment.
This may be due to SHA256 mismatch.

```
% brew tap eclipse-zenoh/homebrew-zenoh
% brew install zenoh
==> Fetching dependencies for eclipse-zenoh/zenoh/zenoh: eclipse-zenoh/zenoh/zenohd, eclipse-zenoh/zenoh/zenoh-plugin-rest, eclipse-zenoh/zenoh/zenoh-plugin-storages and eclipse-zenoh/zenoh/libzenohc
==> Fetching eclipse-zenoh/zenoh/zenohd
==> Downloading https://download.eclipse.org/zenoh/zenoh/0.10.1-rc/aarch64-apple
Already downloaded: /Users/takasehideki/Library/Caches/Homebrew/downloads/e1cac0901dff30652e8a119c15a7520a06cb2dbdebc10bb065196f1a5a67ca06--zenoh-0.10.1-rc-aarch64-apple-darwin.zip
Error: zenoh: SHA256 mismatch
Expected: 8af89b8bf1d20d9d0bd5d440ff4c0532d3ab1e360e056625b5e434f31e0aeb75
  Actual: 03ae125c26d498a83cd91dfc4516f36c0503b595959400bc04907562dfeed19f
    File: /Users/takasehideki/Library/Caches/Homebrew/downloads/e1cac0901dff30652e8a119c15a7520a06cb2dbdebc10bb065196f1a5a67ca06--zenoh-0.10.1-rc-aarch64-apple-darwin.zip
To retry an incomplete download, remove the file above.
```

I tried rewriting the values directly with `brew edit zenoh`, but it did not work correctly.
The binaries [zenoh-0.10.1-rc-aarch64-apple-darwin.zip](https://github.com/eclipse-zenoh/zenoh/releases/download/0.10.1-rc/zenoh-0.10.1-rc-aarch64-apple-darwin.zip) available from Releases are working fine, so there is no immediate problem for me. However, I wanna know the better solution if you have a more appropriate one.

### To reproduce

```
% brew tap eclipse-zenoh/homebrew-zenoh
% brew install zenoh
```

### System info

- Platform: macOS Sonoma (14.2.1)
- CPU: Apple M1 Max (arm64)
- Zenoh version: expected the latest (to be installed from Homebrew)

```
% uname -a
Darwin 192.168.11.104 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
                                                                                
% brew --version
Homebrew 4.2.6-67-g377dbfc
```

**Comment by YuanYuYuan** [comment]
Hi @takasehideki , thanks for your bug reporting. Yes, we can reproduce it. Here's my observation:

```txt
Different versions of zenoh-0.10.1-rc-aarch64-apple-darwin.zip
Expected: 8af89b8bf1d20d9d0bd5d440ff4c0532d3ab1e360e056625b5e434f31e0aeb75  --> 2023-12-21
  Actual: 03ae125c26d498a83cd91dfc4516f36c0503b595959400bc04907562dfeed19f  --> 2024-01-17
```

@fuzzypixelz, maybe we need to re-publish the release of 0.10.1-rc? And our release routine seems to be down for a while. https://github.com/eclipse-zenoh/zenoh/actions/runs/7777656546

**Comment by fuzzypixelz** [comment]
@YuanYuYuan This happened because we had to rebuild artifacts in order to regenerate the Debian packages (they were broken too). I think the simplest solution is to rectify the SHA in homebrew-zenoh.

**Comment by takasehideki** [comment]
@YuanYuYuan @fuzzypixelz Thank you so much! I could confirm the appropriate operation of `brew install zenoh` in my environment after the fix ❤️
