### ISSUE TITLE
Periodic retry on failure to open a listen endpoint

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh#712]
### Describe the feature

Currently Zenoh returns an error on Session opening if it fails to open a configured `listen` endpoint.
Rather to return this error, Zenoh could have the same behaviour than with `connect` endpoints: periodic retry.

This would be better with WiFi for instance, where at host boot the network service might be [online](https://systemd.io/NETWORK_ONLINE/#discussion) but the IP address for WiFi is not yet set by DHCP.

Such behaviour could be configurable (fastfail, retry, period, number of attempts...)

**Comment by Mallets** [comment]
Closed by https://github.com/eclipse-zenoh/zenoh/pull/770
