### ISSUE TITLE
Arm Dockerhub Image

### ISSUE THREAD

**Issue by vinnnyr** [eclipse-zenoh/zenoh#76]
When trying to run the example on a raspberry pi (docker), I get an `Exec Format error`.
```
ubuntu@ubuntu:~$ docker run --init -p 7447:7447/tcp -p 7447:7447/udp -p 8000:8000/tcp eclipse/zenoh
[FATAL tini (6)] exec /entrypoint.sh failed: Exec format error
```

In the past when I have seen this, it is typically due to lack of arm support for the image. Is there an arm dockerhub image available?

**Comment by vinnnyr** [comment]
I can't even build the container myself since there seems to be a dependency on an x86 buildenv (not ssure if I am understanding that correctly)
https://github.com/eclipse-zenoh/zenoh/blob/c3aed63c06c3cbec1013f4f53e2fd65910d4965a/Dockerfile#L16

**Comment by OliLay** [comment]
You can try the image I pushed to `https://hub.docker.com/r/olilay/zenoh-arm64`
Although its either 0.5.0b5 or 0.5.0b7, so already outdated

**Comment by JEnoch** [comment]
Hi @vinnnyr ,

the only Docker image we currently provide is indeed for `amd64` arch.
We need to explore the way to build multi-arch images (including ARMs).
Out of curiosity, which exact ARM architecture are you using: `arm64`, `arm/v7` or `arm/v6` ?

**Comment by JEnoch** [comment]
@OliLay : thanks for this!

BTW, I just release 0.5.0-beta.8, but without the arm64 binary that takes +12 hours to build! (using a `manylinux2014-aarch64` based image which is emulated by Docker on a MacOS...).
How did you build your image : from the `aarch64` binaries we previously released, or do you re-build zenoh on real `amd64` hardware ?

**Comment by OliLay** [comment]
@JEnoch I built zenoh from source on a Raspberry Pi 4 with 4GB RAM. The build takes around 1 hour, so this may be an option for you :)

**Comment by vinnnyr** [comment]
- Will try your docker image, thanks @OliLay 
- @JEnoch I am on `aarch64`. Not sure if that is the right answer to your question but that is the output of `uname -m`
```
ubuntu@ubuntu:~$ uname -m
aarch64
```
- Was running into trouble building from source but will try again and be able to provide more context on the failures (if they happen again, on another ticket)

@OliLay Are you able to share the dockerfile you used to generate the dockerhub image in case I wanted to build the latest version?

**Comment by vinnnyr** [comment]
Oh, I see now that there are instructions how to build the arm image [here](https://hub.docker.com/repository/docker/adlinktech/zenoh-dev-manylinux2014-aarch64-gnu)

**Comment by JEnoch** [comment]
Hi @vinnnyr ,
That's the image I mentioned and that takes +12 hours to build an `aarch64` executable of zenohd and its plugins.
The Dockerfile and instructions to use it are [here](https://github.com/eclipse-zenoh/zenoh/tree/master/docker#zenoh-dev-manylinux2014-aarch64-gnu).
This doesn't build a runnable Docker image with zenohd, but you can adapt [this one](https://github.com/eclipse-zenoh/zenoh/blob/master/Dockerfile) with the result of the `aarch64` build of zenohd and a `aarch64/alpine:latest` as base image.

**Comment by vinnnyr** [comment]
Thanks for the confirmation @JEnoch 

I'll give it a shot here. I think the request here is having this arm build hosted if it is not too many resources for the maintainers side :)

**Comment by JEnoch** [comment]
I understood that 😉 
We'll definitely think about it! That will certainly go with exploration of faster cross-building...

**Comment by vinnnyr** [comment]
82 Mins on an NVIDIA Xavier

**Comment by vinnnyr** [comment]
I also had to play with permissions in the generated target directory and I made the base image ubuntu instead of alpine. (I was getting `/zenohd` not found issues on alpine.
