### ISSUE TITLE
add 'open' function without parameters for create session with default config

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#805]
### Describe the feature

@kydos wrote "I think we should have an overloaded zenoh::open() that does not take the config. Having to create a config just to pass it seems an avoidable step."

**Comment by milyin** [comment]
This could be implemented this way:
```Rust
let s = zenoh::open().wait()?;
...
let s = zenoh::open().peer()?;
...
let s = zenoh::open().client(()?;
...
let c = Config::from_file(file)?;
let s = zenoh::open().config(c).wait()?;
```
I.e. make open function without parameters and add `.config()` setter to `OpenBuilder`

@Mallets what do you think?

**Comment by Mallets** [comment]
The proposal looks good to me and makes the API more coherent.

**Comment by wyfo** [comment]
On my side, I'm against, because I don't think we want the user to use default config. I don't know our user use cases at all, but is there some users that are really using default config in production?

**Comment by wyfo** [comment]
Maybe `scout` could be a better candidate for this kind signature change?

**Comment by Mallets** [comment]
According to latest discussion, `zenoh::open()` will keep accepting `Config` as of Today.
@milyin I believe we can close the issue.

**Comment by wyfo** [comment]
@Mallets Is `scout` a better candidate for a signature rework?
