### ISSUE TITLE
Move shared-memory free-list management out of shared memory segment

### ISSUE THREAD

**Issue by kydos** [eclipse-zenoh/zenoh#85]
The current implementation of zenoh shared memory allocators retrieves the memory for dealing with free list on the shared memory segment. This decision was taken at the time when we considered that a reference dropping to zero would cause a chunk to go back to the free list. However we opted to go for *mark and sweep* garbage collection  that does not require processes to coordinate while operating on the free-list. A a consequence only the process owing the shared-memory segment will do the garbage collection and thus all administration data can be kept on the heap as opposed to the shared memory. 
Thus we should simplify the implementation by using plain rust containers to keep shared memory bookkeeping and allocate these on the heap. This will not only simplify the code but also avoid using shared memory for administration and devoting it completely to user data.

**Comment by kydos** [comment]
This first commit simplifies the code and improves the allocator algorithm. Before closing the issue we need to implement  defragmentation.

**Comment by yellowhatter** [comment]
> SHM support has been heavily reworked in https://github.com/eclipse-zenoh/zenoh/tree/dev/1.0.0, including distributed bookkeeping and reference counting. I believe we can close this issue as outdated and no longer valid.
> 
> Cc @yellowhatter

Sure, let's close it!
