### ISSUE TITLE
Protocol changes: Refactor Liveliness implementation

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/zenoh#864]
A Zenoh application that declares a Liveliness token is monitored internally as if it were a subscriber. However, today the Zenoh protocol defines messages for declaring/undeclaring a "token".

The scope of this issue is to refactor the Liveliness implementation to use `DeclareToken`/`UndeclareToken` messages instead of `DeclareSubscriber`/`UndeclareSubscriber` messages.

The main motivator for this is the current interaction between the Liveliness feature and the `aggregation` configuration option, where a user could technically aggregate subscribers under `@/liveliness/**` which means that a Liveliness subscriber would not be able to distinguish between different monitored Zenoh applications.

**Comment by Mallets** [comment]
Closed by #705 and #865
