### ISSUE TITLE
SHM: Buffer type API

### ISSUE THREAD

**Issue by yellowhatter** [eclipse-zenoh/zenoh#869]
### Describe the feature

We already start getting questions like this:
https://discord.com/channels/914168414178779197/1222489180396064898

From fundamental perspective, I don't like the idea of giving users API to determine the buffer type, as it opens them a way to write configuration-dependent code.

From engineering perspective, it might be useful for some cases if used wisely.
The SHM subsystem is so transparent, that it is not clear for the user if it is properly configured and works.

**Comment by yellowhatter** [comment]
@Mallets tagging you here

**Comment by Mallets** [comment]
This is addressed in the new API in https://github.com/eclipse-zenoh/zenoh/tree/dev/1.0.0.
See https://github.com/eclipse-zenoh/zenoh/blob/73961dd87b66f16160526385d614b53e24422fec/examples/examples/z_sub_shm.rs#L43.

**Comment by yellowhatter** [comment]
@Mallets yes, this issue is old and outdated
