### ISSUE TITLE
Use hash instead of Link to keep track of incoming uninitialized sessions

### ISSUE THREAD

**Issue by J-Loudet** [eclipse-zenoh/zenoh#90]
At the moment, to keep track of the incoming uninitialized sessions we use a `Arc<Mutex<HashSet<Link>>>`.

I suggest we use the hashes of the Cookies instead of the `Link`. That way a peer cannot try to open multiple sessions after performing only one "session initialization".

**Comment by Mallets** [comment]
This [commit](https://github.com/eclipse-zenoh/zenoh/commit/6c3d7cd8f0a19ab6c32062dff50c2f323c1f324f) to the sync branch solves the issue. The sync branch will be then merged into the master branch.
