### ISSUE TITLE
Runtime Agnostic

### ISSUE THREAD

**Issue by teburd** [eclipse-zenoh/zenoh#91]
SQLx managed to avoid locking themselves to tokio/async-std/smol or whatever seemingly by creating a small feature flag driven crate of about 200 loc.

It would be nice to avoid locking this directly to async-std, even if there is a compatibility layer.

https://github.com/launchbadge/sqlx/blob/master/sqlx-rt/src/lib.rs

**Comment by kydos** [comment]
Thanks for the suggestion @bfrog  we'll look into that. We did look closely into Tokio and the main reason for us to pick async-std was that the Sockets have inner mutability. In Tokio there is a split to separate reader and writer half, but the way in which lifetimes work makes it hard to use w/o adding a mutex...

**Comment by teburd** [comment]
@Mallets I believe this can be closed with #566
