### ISSUE TITLE
Unable to use example with UDP only

### ISSUE THREAD

**Issue by r7vme** [eclipse-zenoh/zenoh#911]
### Describe the bug

I'm trying to enforce UDP only by specifying `protocols: ["udp"]` in config and then running `z_pub` and `z_sub`, but example does not work - nothing printed in z_sub.

with debug log I see following warnings

```
[2024-04-07T17:48:17Z WARN  zenoh::net::runtime::orchestrator] Received Hello with no locators: Hello { version: 8, whatami: Peer, zid: ae2d5a4e19f3a6f5380bc7022246ca03, locators: [] }
```

### To reproduce

1. specify `protocols: ["udp"]` in DEFAULT_CONFIG.json5
2. run /target/release/examples/z_sub --config=../zenoh/DEFAULT_CONFIG.json5
3. run /target/release/examples/z_pub --config=../zenoh/DEFAULT_CONFIG.json5

### System info

- Arch Linux
- zenoh main branch b2ef3ddcbd13779553b038b10576e9a761fd015d

**Comment by r7vme** [comment]
I also tried to do the same with router and `peers_failover_brokering: false` (to make sure communicatio will go peer-to-peer, not thru router).

I got following warning in z_sub

```
[2024-04-07T17:54:57Z WARN  zenoh::net::runtime::orchestrator] Unable to connect to any locator of scouted peer 1187c092c2baecca97bec20d59318a00: []
```

Configuration files for router and peers

[DEFAULT_CONFIG_ROUTER.json5.txt](https://github.com/eclipse-zenoh/zenoh/files/14898237/DEFAULT_CONFIG_ROUTER.json5.txt)
[DEFAULT_CONFIG.json5.txt](https://github.com/eclipse-zenoh/zenoh/files/14898238/DEFAULT_CONFIG.json5.txt)

**Comment by r7vme** [comment]
Also found possibly related issue https://github.com/eclipse-zenoh/zenoh/issues/841

**Comment by r7vme** [comment]
Can someone confirm if UDP only is not possible?

**Comment by YuanYuYuan** [comment]
Hi @r7vme , thanks for your question and sorry for the delay.

**Comment by Mallets** [comment]
If you only want to allow `udp`, consider configuring protocol whitelisting: https://github.com/eclipse-zenoh/zenoh/blob/cbeffcf72649855d43b23893b4c8d499623cabc4/DEFAULT_CONFIG.json5#L245

**Comment by r7vme** [comment]
@Mallets thanks, yep to enforce UDP I also use whitelisting. But for example above it was enough to specify endpoint like above. I checked with netstat and ONLY UDP ports were used by z_pub and z_sub
