### ISSUE TITLE
zenohd crushed after receiving several messages

### ISSUE THREAD

**Issue by foobazbarquux** [eclipse-zenoh/zenoh#931]
### Describe the bug

I'm running one zenohd instance and sending several messages with z_put.py , no any additional connections.
backtrace and sh script for reproduce in attachment

### To reproduce

1. Start zenohd : RUST_BACKTRACE=1 ./zenohd -c ../configs/router_second.json5
2. run script: ./m_put_reproduce.sh
[bug.tar.gz](https://github.com/eclipse-zenoh/zenoh/files/14960206/bug.tar.gz)

### System info

Ubuntu 22.04.4 LTS
zenoh main branch 56a44457aac962ba23fbca2f2f9daa663885c4e6
build with cargo build --package zenoh-plugin-storage-manager --package zenohd --profile fast

**Comment by pftbest** [comment]
I can reproduce this on a latest git revision as well, but only in release. The debug build is fine.
