### ISSUE TITLE
check build with different sets of features

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh#940]
Build check with some feature combinations fails at this moment. For example this command fails:
```
> cargo check -p zenoh --tests
...
error[E0425]: cannot find function `init` in crate `zenoh`
   --> zenoh/tests/session.rs:230:25
    |
230 |     let peer01 = zenoh::init(r1.clone()).res_async().await.unwrap();
    |                         ^^^^ not found in `zenoh`
    |
```

but this works ok:

```
cargo check --tests
```

This happens because some features (`unstable` in this particular case) are required by dependent crates and therefore build of base crates passes ok. But by default, when feature is not explicitly specified, build fails. This command works ok:
```
cargo check -p zenoh --tests --features unstable 
```

It's necessary to systematically ensure that build works with at least most of feature combinations and do it for each crate separately

**Comment by milyin** [comment]
@diogomatsubara - this is related to your discussion with Joseph today I think

**Comment by Mallets** [comment]
#1128 added the check for *--no-default-features*

**Comment by Mallets** [comment]
Fixed by https://github.com/eclipse-zenoh/zenoh/pull/1131
